### ISSUE TITLE
About Stripe's build-in card scanning?

### ISSUE THREAD

**Issue by phxgbl** [capacitor-community/stripe#102]
I am using Cordova APP. I have a requirement for bringing stripe build-in card scanning feature to the APP ( https://stripe.dev/stripe-ios/docs/#card-scanning ). does this plugin support build-in card scanning?

**Comment by rdlabo** [comment]
@phxgbl  Yes, this plugin support card-scanning. But you can not use this plugin in  Cordova, please change to capacitor.
https://capacitorjs.com/

![S__9502722](https://user-images.githubusercontent.com/9690024/132454916-34e92ba8-72e3-40fd-a798-c717274a2bd6.jpg)

**Comment by phxgbl** [comment]
@rdlabo Thanks for the quick reply. Actually, we have a Meteor Project here which is pretty old. Meteor is using Cordova behind the scenes for Hybrid App generation. Is there any way to integrate with the existing project without much change?

**Comment by rdlabo** [comment]
@phxgbl Sorry, I don't have experience of using Meteor. But starting Capacitor is easy for me.

**Comment by rdlabo** [comment]
I look You don't have more issue on this plugin. so I will close this issue. Thanks.

**Comment by rdlabo** [comment]
@phxgbl Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
