### ISSUE TITLE
Subscriptions and language

### ISSUE THREAD

**Issue by Marius-Romanus** [capacitor-community/stripe#103]
Hello, I have two questions:

Is this valid for subscriptions?
Can the texts of "Pay", "Add your payment information", etc be changed?

Thanks!

**Comment by rdlabo** [comment]
@Marius-Romanus  Maybe yes. Difference of payment once or subscription looks loke on backend only.

> Can the texts of "Pay", "Add your payment information", etc be changed?

No, this is be from stripe's SDK. We can use multi language, but can't change arbitrarily.

**Comment by Marius-Romanus** [comment]
thank you, how can I change the language?

**Comment by rdlabo** [comment]
Device's settings of language. But this is not plugin issue, if you want to know detail, please ask stripe team.

**Comment by Marius-Romanus** [comment]
Right, thanks for the help

**Comment by rdlabo** [comment]
@Marius-Romanus Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
