### ISSUE TITLE
iOS: Blank payment sheet appears for a second and then disappears

### ISSUE THREAD

**Issue by MohamedRed** [capacitor-community/stripe#106]
I am facing this issue: I manage to create a new PaymentIntent, I then call createPaymentSheet(), then presentPaymentSheet(), then a blank payment sheet appears for a second and then disappears with the error paymentResult.failed.

I have also tried with Apple Pay. Everything works fine with Apple pay until I pay then it fails with also paymentResult.failed.

I haven't figured out what I am missing.

**Comment by rdlabo** [comment]
@MohamedRed  Please try [demo](https://github.com/capacitor-community/stripe/tree/master/demo) 

There is a high possibility that there is a problem with the server. Is paymentIntent  right? Start your investigation from there.

**Comment by MohamedRed** [comment]
When I restarted my endpoint, the payment sheet worked fine. 
Apple pay was still not working because I missed the step consisting in adding the ios certificate to my Stripe payment methods settings.
Now it all works fine.
Thanks a lot for your hard work.

**Comment by rdlabo** [comment]
@MohamedRed Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
