### ISSUE TITLE
Apple rejected the app due to missing "Merchant name" on the apple pay payment sheet

### ISSUE THREAD

**Issue by flavioribeirojr** [capacitor-community/stripe#115]
**Describe the bug**
My app got rejected using the stripe plugin because there is no merchant name that the user can see on apple pay Payment Sheet.

**To Reproduce**
Create and open the apple pay sheet

**Expected behavior**
I need to be able to show a merchant name on the apple pay payment sheet

**Screenshots**
![image](https://user-images.githubusercontent.com/21633230/137347219-0ccea207-1e98-4ac9-b3f4-578eaec77600.png)

**Smartphone:**
 - Device: iPhone 1 1 Pro Max
 - OS: ios 14

Is there any way to display the merchant name after the "PAY" text?

**Comment by flavioribeirojr** [comment]
I was able to resolve this. You can display the merchant name by adding it as the last **Summary Item**. Ex.:

```
const summaryItems = [
    ...itemsInPurchase,
    {
        label: 'Food Company Inc.',
        amount: 50 // This needs to be the purchase total
    }
]

**Comment by rdlabo** [comment]
@flavioribeirojr Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.

**Comment by nicks78** [comment]
Hello, 
I have the same issue with @stripe/stripe-react-native V0.19.0, I have tried your fixed but the merchant name does not appear on apple pay popup window so apple rejected my app. 
`const response = await presentApplePay({
            cartItems: [
                {
                    label: "My CompanyName Limited",
                    amount: "0.00",
                    paymentType: "Deferred",
                    deferredDate: Date.now(),
                },
            ],
            country: CONFIG_PAYMENT.country,
            currency: CONFIG_PAYMENT.currency,
        });`

**Comment by top-kat** [comment]
@nicks78 have you managed to resolved that ? 

I have the same problem with `"@stripe/stripe-react-native": "0.23.3"` and `"react-native": "0.71.8"`

**Comment by top-kat** [comment]
Finally I managed to solve this by **setting the payment type to `Immediate` instead of `defered`. 

A lot of trial and errors to fix that 🥵 Hope it helps

Here is my before / after code:

<img width="1143" alt="image" src="https://github.com/capacitor-community/stripe/assets/17770809/a2a5a8ec-80c7-4d8a-bc3f-4e146d547f23">
