### ISSUE TITLE
Will this work without having issues of SSL on mobile devices

### ISSUE THREAD

**Issue by stickypages** [capacitor-community/stripe#118]
I implemented Stripe in my app, but it won't work on mobile devices because there is no SSL for payments. Then I found your plugin, and curious to know how does this work-around security (SSL) on native app devices? 

Just a bit new to mobile payment implementation here. Thanks!

**Comment by hideokamoto** [comment]
Just using the Stripe SDK or Stripe Element.

https://stripe.com/payments/elements

**Comment by stickypages** [comment]
So you don't think I will run into issues with SSL/HTTPS with payments using your plugin? Because I'm using Stripe Elements right now with Payment Intent, and it mentions in the logs that cannot serve this over HTTP/LocalHost. 

What am I missing?

**Comment by hideokamoto** [comment]
In the mobile device, we're using Stripe official SDK to provide a payment sheet.
https://stripe.com/docs/payments/quickstart

And the Stripe docs does not says about SSL.

Could you share us more detail what you suffering? If you share us the step of reproduce, we can check it in our env.

**Comment by stickypages** [comment]
I am not using your plugin yet, but wanted to ask about the SSL before converting my code to use your plugin. I will give it a try and hope that it works smooth. Thanks for the heads-up, I will report back in case someone else is looking for this.

**Comment by hideokamoto** [comment]
Ok thank. If you get any error that comes from SSL, please report us in here.I’ll check it and help to resolve if.

FYI

If you want to get certain answer before using the plugin, please contact to the Stripe support team.
You can ask them like the question. “Is the Stripe iOS/Android SDK needs to use SSL?”

Because the plugin is using these SDKs in a native devices. So the behavior may be almost same as these Native SDKs.

**Comment by stickypages** [comment]
Awesome thanks for the heads-up. That's great. I was just using the JS url import of Stripe. I will give this a shot, fingers crossed.

**Comment by stickypages** [comment]
@hideokamoto So far I'm continuing to get error on "Missing Argument" Make sure to call mount() with valid DOM element. No Card input.

I am using Vue.js (Nuxt). and have the defineComponents where I init Vue
```
import { defineCustomElements } from '@stripe-elements/stripe-elements/loader'
defineCustomElements(window).then((res) => {
  console.log('defineCustomElements', res) // returns NULL
})
```

On the page I am calling Stripe. I use... is there something else i'm missing for setup?
```
onMounted(() => {
    await Stripe.initialize({
        publishableKey: 'pk_test_51JPFp9KFs....................'
    })
})
```

Was also missing the SVG Close.

![image](https://user-images.githubusercontent.com/658488/139729294-8dbb1485-4c00-45ae-8da2-4ecc3dfbdc41.png)

![image](https://user-images.githubusercontent.com/658488/139729390-8036609a-bdd5-4364-a8c3-58756410362c.png)

**Comment by stickypages** [comment]
I am testing locally, I thought it might be related to using HTTP, so I setup a SSL cert for local development, could this be an issue using a local (self-signed) CERT vs, a properly signed one?

**Comment by stickypages** [comment]
Just thought I would share my latest findings. Would appreciate any knowledge on how to get the credit card input to show up. I've been at this for days and cannot get the sheet to fully show up on Web version.

![image](https://user-images.githubusercontent.com/658488/140004342-cceb9362-082f-4e22-97b7-7546f52a6813.png)

**Comment by stickypages** [comment]
I have now found out that I had a conflict within one of my Nuxt Stripe Modules. I have removed it and it solved the card information for not showing.

**Comment by stickypages** [comment]
Just wanted to give a 'heads-up'. I was able to get it all to work. getting accurate messages from Stripe and updating the database just fine without SSL issues.

**Comment by hideokamoto** [comment]
Thanks for trying to use this plugin in the Vue application!
Probably it's the first application that uses this plugin and Vue :)

If possible, could you share the application repo? 
We're interested in the use case in Vue.

**Comment by stickypages** [comment]
Hey, I cannot share the repo unfortunately, because it's private. But I will try to put together what I did.

**Comment by hideokamoto** [comment]
Thanks!!
It's really helpful for us:)

**Comment by ciccilleju** [comment]
> 
hello, i hope it can be helpful:

![image](https://user-images.githubusercontent.com/42606234/143497473-935bd121-2f5b-4166-a10a-138a9a288005.png)

They (stripe customer service) confirmed that I need to go over https for those wallet payments, while credit card payment works fine on http even if they suggest to use https.

And if I run the app on my Ionic /capacitor 3 App, i can only see the credit card,
if i run on a webserver with https that's what I see:

![image](https://user-images.githubusercontent.com/42606234/143497692-ea1a2473-dfba-4a97-9dc1-0effd00238e0.png)


![image](https://user-images.githubusercontent.com/42606234/143497563-322acdf0-24df-4a74-b76d-447ca54018ca.png)

**Comment by stickypages** [comment]
So the question is.... is the transaction secure or not?

**Comment by rdlabo** [comment]
@ciccilleju Sorry, this is not plugin funtion.

**Comment by rdlabo** [comment]
Is this issue resolved? This don't has any update, so will close. If be update, please re-open.
Thanks.
