### ISSUE TITLE
ANDROID presentPaymentSheet issue

### ISSUE THREAD

**Issue by giuseeFG** [capacitor-community/stripe#120]
hi!

the method "presentPaymentSheet" works fine in iOS, it returns all data correctly.

BUT on Android it doesn't work the very first time. It works fine from the second time on.
So I cannot have the result the first time I call the function.

Why?!

**Comment by appkro** [comment]
I'm have the same problem, any solution?

**Comment by hideokamoto** [comment]
Hi!
Is it possible to share the error log about the issue?
Or does not error happen? (Just not showing the modal)

Thanks.

**Comment by appkro** [comment]
It does not generate an error, the payment modal is not lifted, the second time the modal is opened it opens correctly.

**Comment by ciccilleju** [comment]
> It does not generate an error, the payment modal is not lifted, the second time the modal is opened it opens correctly.

can you paste a code snippet from your app? 

(ciao Giuseppe, se vuoi scrivimi un messaggio privato, diamo un'occhiata al codice)

**Comment by appkro** [comment]
![Captura de pantalla de 2021-12-01 15-34-41](https://user-images.githubusercontent.com/89037647/144309906-7a7bde4a-6a6e-427e-8991-66cf1f775e0d.png)

**Comment by rdlabo** [comment]
Has this problem been resolved? No action taken, so this Issue is closed. If you continue to have problems, please create a new Issue.
