### ISSUE TITLE
Should we return boolean in the `isApplePayAvailable` and `isGooglePayAvailable` method?

### ISSUE THREAD

**Issue by hideokamoto** [capacitor-community/stripe#124]
I think these methods should return `boolean`.
And we can use the returned attributes to change the UI behavior.

```jsx
if (!Stripe.isGooglePayAvailable()) {
  return null
}
return (
  <button>Pay with Google</button>
)
```

Can we replace these behavior?

**Comment by rdlabo** [comment]
Thanks. Capacitor Plugin's method must be Promise base. so I think  `is**Available` should be resolve/reject .

**Comment by junkycoder** [comment]
I had the same thoughts @hideokamoto, but I understand @rdlabo. However here is a some sugar code I use to getting a boolean on a call:
```js
function boolifyPromise(promise) {
  return promise.then(() => true).catch(() => false);
}

//
const isApplePayAvailable = await boolifyPromise(Stripe.isApplePayAvailable());
if (!isApplePayAvailable) {
  return null;
}

```
