### ISSUE TITLE
Customization of browser opened while processing payment

### ISSUE THREAD

**Issue by raghuchaharsqm** [capacitor-community/stripe#128]
Is there any way we can customize the browser page opened while processing payment using any of payment sheet or payment flow method, I did some research there was ways to customize checkout page but I found nothing related to customization of browser.
Please help me out in this 
Thanks

**Comment by rdlabo** [comment]
You don't have to use this plugin in web. You can use https://stripe.com/docs/payments/elements for create custom field.
Thanks.

**Comment by raghuchaharsqm** [comment]
> You don't have to use this plugin in web. You can use https://stripe.com/docs/payments/elements for create custom field. Thanks.

Thanks @rdlabo , but I am not using this in web i am using this in mobile app itself.

**Comment by rdlabo** [comment]
@raghuchaharsqm Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
