### ISSUE TITLE
Choose the payment method

### ISSUE THREAD

**Issue by loicparent** [capacitor-community/stripe#130]
_Hello,_

I arrive to process the payment using ApplePay - GooglePay - PaymentSheet.
I just have to detect the device and then select the payment method adapted.

When I look at the website of Stripe, I see that the payment screen let the user choose between the "native" payment (e.g. ApplePay) or the Cart Payment:
![stripe_payment_screen](https://user-images.githubusercontent.com/11327909/145381546-e9c39d59-31f8-45c2-99e7-fe52619eb350.png)

So I was wondering if there is a way to do the same thing using this plugin.
I know I can show the buttons by myself but this would be outside the payment modal and so this add one more step in the payment process. Therefore, I would prefer if this is include in the Stripe Plugin.

Could you tell me if this is possible at the moment using this plugin?

_Thanks and have a nice day!_
_Loïc_

**Comment by rdlabo** [comment]
May be enable: https://github.com/capacitor-community/stripe/blob/master/src/shared/index.ts#L34-L69

But due to the addition of the button, this feature has not been fully tested. try it. Thanks.

**Comment by loicparent** [comment]
Thanks for you reply @rdlabo!

I will look over this.

_Regards_

**Comment by rdlabo** [comment]
@loicparent Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.

**Comment by loicparent** [comment]
Hello @rdlabo,

For the moment, we are working on setting up the payment system using this plugin but this is not yet finished and so this is not currently on production.

I will add a comment in the discussion "What App Use Stripe Plugin?" if/when the changes go on production 😉

FYI the app is Totemus
💻  https://totemus.be
🍎  https://apps.apple.com/fr/app/totemus/id1496178920
🤖  https://play.google.com/store/apps/details?id=be.noomia.totemus&hl=fr&gl=US
