### ISSUE TITLE
Save and Reuse

### ISSUE THREAD

**Issue by supportreq** [capacitor-community/stripe#132]
**Is your feature request related to a problem? Please describe.**
In the Ionic-Stripe is there a way to save and reuse the card. This will allow the user to just confirm his CVV number and be able to make the payment using the stored Card.

Stripe official documentation has option for React Native but not for Ionic

https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet

Please advice.

**Comment by ciccilleju** [comment]
You can do it.
As long as I remember I call 2 functions: 
one for reading if the customer has already made a payment with stripe and if has a default card (so he has a stripe token stored in the DB) and the other one for adding a card.

this is an example with Ionic I have made years ago

![image](https://user-images.githubusercontent.com/42606234/146895185-cd9d2d35-6e6c-44b2-bec6-424e4f635199.png)
![image](https://user-images.githubusercontent.com/42606234/146895304-1b46ed5f-e8da-487f-ba73-21dd50e9ee9a.png)
![image](https://user-images.githubusercontent.com/42606234/146895434-52cf8caf-4c25-43dd-9297-470838844dcc.png)

**Comment by rdlabo** [comment]
@supportreq You can use setupIntent in PaymentSheet or PaymentFlow.

**Comment by rdlabo** [comment]
Is this issue resolved? This don't has any update, so will close. If be update, please re-open.
Thanks.

**Comment by rdlabo** [comment]
@supportreq Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
