### ISSUE TITLE
Stripe Capacitor Plugin Size?

### ISSUE THREAD

**Issue by ciccilleju** [capacitor-community/stripe#133]
Hello!
Just one question:

My app, before installing the Capacitor Plugin, was 6,8 mb (released with the--prod flag)

Now, it's 18 mb

Is it normal or do I need to set something?

thanks

**Comment by ciccilleju** [comment]
I didn't need to follow the steps described here:
https://stripe.com/docs/google-pay

**Comment by rdlabo** [comment]
Is this web bundle size, or android package size? Probably the size of Android, but it's the size of the Stripe SDK. This is not plugin issue. You should create issue on https://github.com/stripe/stripe-android .

Thanks.

**Comment by ciccilleju** [comment]
> Is this web bundle size, or android package size? Probably the size of Android, but it's the size of the Stripe SDK. This is not plugin issue. You should create issue on https://github.com/stripe/stripe-android .
> 
> Thanks.

Hello! 
thank you for your reply.
I'm talking about the Android Apk, you are right.

thanks!

**Comment by rdlabo** [comment]
Thanks for reply. This plugin is only simple wrapper👍

**Comment by ciccilleju** [comment]
> Thanks for reply. This plugin is only simple wrapper👍

You are doing a great job, thank you so much for everything!
