### ISSUE TITLE
paymentSheet.present is not a function

### ISSUE THREAD

**Issue by zulkarnainfaizan** [capacitor-community/stripe#141]
**Describe the bug**
Not able to present card action sheet in my ionic app  when implementing Payment Sheet part:
I am getting this error:
**TypeError: _this3.paymentSheet.present is not a function
    at web.ts:74
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new ZoneAwarePromise (zone.js:1340)
    at asyncToGenerator.js:21
    at StripeWeb.presentPaymentSheet (web.ts:67)
    at index.js:196
    at ZoneDelegate.invoke (zone.js:400)**
**on this function**
```
export async function present(): Promise<void> {
  const result = await Stripe.presentPaymentSheet();
}
```
**screenshot**
![image](https://user-images.githubusercontent.com/19909522/147448825-5fb5bbb6-5b4d-4f52-a454-df0eb72e9a76.png)

**Comment by mengoni** [comment]
Hi,
I experienced the same issue and solved upgrading stripe elements package to 1.0.0

`    
"@capacitor-community/stripe": "^3.4.2",
"@stripe-elements/stripe-elements": "1.0.0",
`

Hope it helps

**Comment by rdlabo** [comment]
Please console.log(this.paymentSheet); This may not be plugin issue.

**Comment by rdlabo** [comment]
Is this issue resolved? This don't has any update, so will close. If be update, please re-open.
Thanks.

**Comment by rdlabo** [comment]
@zulkarnainfaizan @mengoni Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.

**Comment by prabhjotAppmobi** [comment]
I am getting the same issue in version 4.0.0? is there any approach to solve it?

**Comment by redisdead84** [comment]
me too

**Comment by ayubUOL** [comment]
Any update for this issue? I'm trying to integrate it in ionic capacitor.

**Comment by giuseeFG** [comment]
any news about this issue?
