### ISSUE TITLE
iOS: build not approved because Apple Pay misses " Merchant's name on the payment sheet"

### ISSUE THREAD

**Issue by ciccilleju** [capacitor-community/stripe#143]
hello,
i was submitting a bug fixing to my app already present in the iOS store but today they refused it because of this message:
![image](https://user-images.githubusercontent.com/42606234/147851951-2258a97c-e1c5-4668-98cf-0513f005468b.png)

this is my code related to Apple Pay:

`async createApplePay(): Promise<void> {

    let requestUrl = this.generateStripeIntentWallet;
    let postData = { idOrdine: this.idOrdine };
    this.http.doPostApplicationJsonBearer(requestUrl, postData, this.myService.tokenValue).subscribe((res => {
      this.paymentIntent = res.id;
      Stripe.createApplePay({
        paymentIntentClientSecret: res.client_secret,
        paymentSummaryItems: [{
          label: this.utilsOmbrelloniProvider.idOrdine,
          amount: this.utilsOmbrelloniProvider.totale
        }],
        merchantIdentifier: 'mymerchant.xxxxxx',
        countryCode: 'IT',
        currency: 'EUR',
      }).then(() => {
        Stripe.isApplePayAvailable().then(() => this.isApplePayAvailable = true);
      }).catch(error => {
        console.log(error);
      });

    }));
  }`

this is what i found in the iterface:
`export interface CreateApplePayOption {
    paymentIntentClientSecret: string;
    paymentSummaryItems: {
        label: string;
        amount: number;
    }[];
    merchantIdentifier: string;
    countryCode: string;
    currency: string;
}
export interface CreateGooglePayOption {
    paymentIntentClientSecret: string;
}
`

I don't see any variable related to the merchant's name.

How can I solve this problem with Apple? There is any way to set Merchant's name on the payment sheet?

![image](https://user-images.githubusercontent.com/42606234/147852000-3a753cf4-5143-46fe-a894-bd0ffed1161e.png)

**Comment by rdlabo** [comment]
This seems solved issue: https://github.com/capacitor-community/stripe/issues/115

**Comment by ciccilleju** [comment]
excellent,

thank you so much,

i'll send a new build right now!

fingers crossed :)

**Comment by rdlabo** [comment]
@ciccilleju Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.

**Comment by ciccilleju** [comment]
> @ciccilleju Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022. #145 Thanks.

hello! I thik 've solved adding our app name to "label"

**Comment by rdlabo** [comment]
@ciccilleju Hi, thanks for quick response! We want to know your app name.
If possible, please write to https://github.com/capacitor-community/stripe/issues/145 . Thanks.

**Comment by ciccilleju** [comment]
> @ciccilleju Hi, thanks for quick response! We want to know your app infomation. If possible, please write to #145 . Thanks.

Will do within one hour
