### ISSUE TITLE
Request for Digital Wallets / Bank transfer features

### ISSUE THREAD

**Issue by dodomui** [capacitor-community/stripe#144]
**Describe the solution you'd like**
Looking for following features for South-east Asia market.
1. Digital wallets for Malaysia, Singapore, and Hong Kong?
2. Bank transfer for Malaysia, FPX

**Comment by hideokamoto** [comment]
Are these payment method supported by Stripe yet?

**Comment by dodomui** [comment]
@hideokamoto Yes, all of them are supported by Stripe.

**Comment by rdlabo** [comment]
Thanks for request. We had same request already, and We will this at future: https://github.com/capacitor-community/stripe/issues/88

But these function can't use in Japan... ( me and @hideokamoto is in Japan ).
We will start it someday, but welcome to create a pull request.

**Comment by rdlabo** [comment]
@dodomui Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145

**Comment by dodomui** [comment]
@rdlabo I didn't use this plugin for production.

**Comment by rdlabo** [comment]
@dodomui Thanks for information! If use for production. please tell to https://github.com/capacitor-community/stripe/issues/145 !

**Comment by grzesebe** [comment]
#201

**Comment by rdlabo** [comment]
This is a duplicate of https://github.com/capacitor-community/stripe/issues/88 , so it is closed.
