### ISSUE TITLE
[Android] Google Pay in production mode seems doesn't work

### ISSUE THREAD

**Issue by FY0u11** [capacitor-community/stripe#148]
**Describe the bug**
Hello everyone and thanks for this plugin. I did everything like described in documentation and it's working fine when google_pay_is_testing is true but when time is come to roll out our app to production (We changed google_pay_is_testing to true and replaced Stripe keys with live ones), the plugin stopped to work.

**To Reproduce**
1. Change google_pay_is_testing from true to false.
2. See error

**Expected behavior**
It should work in prod mode

**Screenshots**
![photo_2022-01-27_11-02-18](https://user-images.githubusercontent.com/48677295/151295075-17dd462a-60b8-46d9-9b43-4d927fd90b46.jpg)

**Smartphone (please complete the following information):**
 - Device: Meizu 18
 - OS: Android 11

**Comment by rdlabo** [comment]
This issue may support you : https://github.com/stripe/stripe-react-native/issues/730

And please check documentation: https://stripe.capacitorjs.jp/docs/google-pay

**Comment by rdlabo** [comment]
Has this problem been resolved? No action taken, so this Issue is closed. If you continue to have problems, please create a new Issue.
