### ISSUE TITLE
npx cap sync fails - AMSupportURLConnectionDelegate implemented twice

### ISSUE THREAD

**Issue by travisBradfield** [capacitor-community/stripe#152]
**Describe the bug**
I'm able to run: 
`npm install @capacitor-community/stripe`

When I run the: `npx cap sync` it fails on the pod install wit the following error: 

```
Analyzing dependencies
objc[19147]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x213126b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1086d82c8). One of the two will be used. Which one is undefined.
```

**To Reproduce**
1. `npm install @capacitor-community/stripe`
2. `npx cap sync`
3. Error.

**Expected behavior**
I expect the pod install and cap sync to be successful. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.1 (M1)

**Comment by travisBradfield** [comment]
Is the M1 situation a contributor to this problem?

**Comment by rdlabo** [comment]
Does this article help you? : https://stackoverflow.com/questions/65089767/class-amsupporturlconnectiondelegate-is-implemented-in-both

My machine is M1, but this error doesn't happen.

**Comment by travisBradfield** [comment]
Thanks for your response! 

Do you know what my target iOS version should be? At this point that article isn't helping me yet..

**Comment by travisBradfield** [comment]
So after some trying what seemed to work for me was running: 

sudo gem install cocoapods -n /usr/local/bin

**Comment by rdlabo** [comment]
@travisBradfield  I'm glad you got it sorted out!

Did you use this plugin for production? If yes, please tell us what app. This help development this plugin.

👉  https://github.com/capacitor-community/stripe/issues/145

Thanks.

**Comment by travisBradfield** [comment]
Thanks for your help! Not in production yet, but it will be going out in the next few weeks.

**Comment by rdlabo** [comment]
Thanks. I can't wait to hear of your release!

**Comment by rdlabo** [comment]
Has this problem been resolved? No action taken, so this Issue is closed. If you continue to have problems, please create a new Issue.
