### ISSUE TITLE
Googlepay pop-up issue

### ISSUE THREAD

**Issue by curiousShreya** [capacitor-community/stripe#173]
**Describe the bug**
I have followed this repo to integrate googlepay to my mobile application using ionic. The final googlepay pop-up window is taking my already saved email id, the saved mastercard but after that there is no amount to pay or pay button is displaying instead "Continue" button is displaying and when I clicked on that button my application is crashing so can you please suggest some methods and options to rectify this issue.

**To Reproduce**

**Expected behavior**
In the screenshots sections, I shared the link of your googlepay screenshot and in this screenshot, you can see the payment amount and the "Pay" button. My application is displaying the mail-ID and the card details but not getting this payment amount and the "Pay" amount instead I am just getting a "Continue" button and on clicking this button my application is crashing so how can I rectify this issue.

**Screenshots**
https://github.com/capacitor-community/stripe/blob/master/demo/screenshots/google-pay-android.png

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [SM-M307F/DS]
 - OS: [android]
 - Browser [CHROME]

**Additional context**

**Comment by rdlabo** [comment]
@curiousShreya Did you set paymentSummaryItems??
demo: https://github.com/capacitor-community/stripe/blob/master/demo/angular/src/app/tab1/tab1.page.ts#L230-L233

And make sure the last line contains the total amount. This is the same specification as Apple Pay.
https://github.com/capacitor-community/stripe/blob/master/src/web.ts#L299

**Comment by rdlabo** [comment]
And please try v3.7.0. Thanks.

**Comment by curiousShreya** [comment]
Okay. Also, there is a thing that i have used ionic React in googlepay integration and the doc you have shown me uses Angular so does it make any difference?

**Comment by rdlabo** [comment]
Has this problem been resolved? No action taken, so this Issue is closed. If you continue to have problems, please create a new Issue.
