### ISSUE TITLE
[Web Issue] Google Pay Web: method isGooglePayAvailable() throws still 'Not implemented on web.' 

### ISSUE THREAD

**Issue by mendo96** [capacitor-community/stripe#175]
**Describe the bug**
The google pay in android works fine, but when i open it on the web (firefox,chrome, safari tested) i get the error message: 'Not implemented on web.'

**Expected behavior**
A google pay button should be available on the web without any error message.

**Screenshots**
My Code: 
<img width="566" alt="Bildschirmfoto 2022-04-16 um 15 14 17" src="https://user-images.githubusercontent.com/47355180/163676334-32faf9ac-04e9-49ee-8d3c-d7deea3f56c0.png">

Error msg:
<img width="813" alt="Bildschirmfoto 2022-04-16 um 15 17 52" src="https://user-images.githubusercontent.com/47355180/163676464-b5e7d798-11ff-48f9-a895-b466fa822d8e.png">

**Desktop**
 - OS: MacBook M1
 - Browser [chrome, safari,firefox]

**Additional context**
my package json:

{
  "name": "XXXX",
  "version": "1.0.0",
  "author": "XXXX",
  "homepage": "",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^13.1.2",
    "@angular/cdk": "^13.1.2",
    "@angular/common": "^13.1.2",
    "@angular/core": "^13.1.2",
    "@angular/fire": "^6.1.5",
    "@angular/forms": "^13.1.2",
    "@angular/material": "^13.1.2",
    "@angular/platform-browser": "^13.1.2",
    "@angular/platform-browser-dynamic": "^13.1.2",
    "@angular/router": "^13.1.2",
    "@capacitor-community/apple-sign-in": "^1.0.1",
    "@capacitor-community/facebook-login": "^3.3.0",
    "@capacitor-community/http": "^1.4.1",
    "@capacitor-community/stripe": "^3.6.0",
    "@capacitor-community/twitter": "^1.0.1",
    "@capacitor/android": "^3.4.3",
    "@capacitor/app": "^1.1.1",
    "@capacitor/browser": "^1.0.7",
    "@capacitor/camera": "^1.3.1",
    "@capacitor/clipboard": "^1.0.8",
    "@capacitor/core": "^3.4.3",
    "@capacitor/geolocation": "^1.3.1",
    "@capacitor/haptics": "^1.1.4",
    "@capacitor/ios": "^3.4.3",
    "@capacitor/keyboard": "^1.2.2",
    "@capacitor/push-notifications": "^1.0.9",
    "@capacitor/share": "^1.1.2",
    "@capacitor/splash-screen": "^1.2.2",
    "@capacitor/status-bar": "^1.0.8",
    "@capacitor/storage": "^1.2.5",
    "@codetrix-studio/capacitor-google-auth": "^3.0.2",
    "@google-cloud/firestore": "^5.0.2",
    "@google-pay/button-angular": "^3.0.0",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/diagnostic": "^5.36.0",
    "@ionic-native/native-geocoder": "^5.36.0",
    "@ionic/angular": "^6.1.0",
    "@ionic/cli": "^6.19.0",
    "@ionic/pwa-elements": "^3.1.1",
    "@robingenz/capacitor-android-dark-mode-support": "^1.0.1",
    "@thetsf/geofirex": "^0.1.3",
    "@types/googlemaps": "^3.43.3",
    "capacitor-native-biometric": "^3.1.0",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova.plugins.diagnostic": "^6.1.1",
    "cupertino-pane": "^1.2.82",
    "firebase": "^8.8.1",
    "ng-circle-progress": "^1.6.0",
    "ng-otp-input": "^1.8.5",
    "ngx-image-compress": "^13.1.5",
    "ngx-sortablejs": "^11.1.0",
    "rxjs": "^7.5.5",
    "scriptjs": "^2.5.9",
    "sortablejs": "^1.15.0",
    "tslib": "^2.3.1",
    "zone.js": "^0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1303.3",
    "@angular-devkit/build-angular": "^13.1.3",
    "@angular/cli": "^13.1.3",
    "@angular/compiler": "^13.1.2",
    "@angular/compiler-cli": "^13.1.2",
    "@angular/language-service": "^13.3.3",
    "@capacitor/cli": "^3.4.3",
    "@ionic/angular-toolkit": "^6.1.0",
    "@ionic/lab": "^3.2.11",
    "@types/jasmine": "^4.0.2",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^17.0.24",
    "@types/sortablejs": "^1.10.7",
    "agm-overlays": "^2.0.0",
    "codelyzer": "^6.0.2",
    "firebase-tools": "^10.6.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^8.2.2",
    "inquirer-autocomplete-prompt": "^2.0.0",
    "jasmine-core": "^4.1.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "^6.3.18",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "^5.0.0",
    "karma-jasmine-html-reporter": "^1.7.0",
    "open": "^8.4.0",
    "protractor": "~7.0.0",
    "ts-node": "^10.7.0",
    "tslint": "~6.1.0",
    "typescript": "^4.4.4"
  },
}

**Comment by nxj1129** [comment]
Could you show a snippet of the code you used for google pay button? For me it doesn't work on android. I have also commented on issue #174 
The isGooglePayAvailable() always throws an error on my android that Google Pay is not implemented. I have followed all the documentation and cannot see where the problem is since the code is all the same. Everything is installed and setup properly.
Tested on Samsung S8, Android 9, Capacitor 3.6.0

**Comment by rdlabo** [comment]
This is same issue of https://github.com/capacitor-community/stripe/issues/174

**Comment by mendo96** [comment]
@rdlabo  its not the same issue, because on android it works, but in web it does not work, i get this error with 'no implenented on **web**', the issue that u mentioned throws other error : 'not implemented on **device**'

**Comment by rdlabo** [comment]
@mendo96 https://github.com/capacitor-community/stripe/issues/174 is web issue: screenshot is Chrome's devtool.

And sorry, maybe reason is that I forgot to release current version. Now released v3.7.0. Please try this.
Thanks.

**Comment by mendo96** [comment]
Hey thank you for releasing the new version :),

Now i get a different error:
<img width="881" alt="Bildschirmfoto 2022-04-22 um 11 22 02" src="https://user-images.githubusercontent.com/47355180/164677384-3d47ab11-0daa-466d-bc68-a9ab643eb4e9.png">

There is always a "null" error from the package and "this device can not use".

I tested that on firefox, chrome and safari. 

My code: 

<img width="550" alt="Bildschirmfoto 2022-04-22 um 11 23 52" src="https://user-images.githubusercontent.com/47355180/164677546-bd48379f-2086-4bab-8c4a-d75573eaab8e.png">

**Comment by rdlabo** [comment]
Oh, I see. Please try 

```bash
% npm i @stripe-elements/stripe-elements@1.1.0-10
```

It has not been released yet. I will check with the people concerned, but please try this first.
Thanks.

**Comment by mendo96** [comment]
Still the same issue, but different logs:

<img width="773" alt="Bildschirmfoto 2022-04-22 um 11 56 17" src="https://user-images.githubusercontent.com/47355180/164683734-f7728738-6833-43d2-82bf-cdba8ad88eeb.png">

**Comment by rdlabo** [comment]
Mumu...
Please try https://capacitor-community-stripe.netlify.app/ . This hosted master branch, and use tested intent. 
Can you first check if it works properly in your environment?

**Comment by rdlabo** [comment]
OK. And I notice. Your environment is not https.
Please check this: https://stripe.com/docs/stripe-js/elements/payment-request-button?platform=html-js-testing-google-pay

Google Pay is only work https environment.

**Comment by mendo96** [comment]
Ill check that later, i deploy the app as https :) 
your link https://capacitor-community-stripe.netlify.app/ only works in chrome, the other browsers like safari and firefox do not work, the create google pay button is disabled

**Comment by mendo96** [comment]
The button can now be displayed using https and chrome. However, this error appears when executing the payment: 
<img width="450" alt="Bildschirmfoto 2022-04-22 um 17 39 55" src="https://user-images.githubusercontent.com/47355180/164748852-65605942-b1ae-4e70-b56d-f96a299368fc.png">

My code for creating the payment to send to the server:

<img width="370" alt="Bildschirmfoto 2022-04-22 um 17 44 28" src="https://user-images.githubusercontent.com/47355180/164748916-2a5c0096-07c4-4020-a4df-f0e2bbda5f02.png">

i guess, the amount should be a string or sth like that?

**Comment by rdlabo** [comment]
> only works in chrome

Yes, It is an accurate behavior.

<img width="848" alt="スクリーンショット 2022-04-23 午後5 45 41" src="https://user-images.githubusercontent.com/9690024/164887461-ff2354b0-520c-400a-ae12-7e6f0d290088.png">

**Comment by rdlabo** [comment]
> The button can now be displayed using https and chrome. However, this error appears when executing the payment:

Please search error text in Google. This error may not reason from plugin.

**Comment by mendo96** [comment]
Okay, thank you for your help, i appreciate it
