### ISSUE TITLE
Documentation and Example page missing

### ISSUE THREAD

**Issue by syshex** [capacitor-community/stripe#18]
**Describe the bug**

at this page:  https://capacitor-community.github.io/stripe/

the links to Documentation and examples point to : 
  . https://zyra.github.io/capacitor-stripe/installation
 . https://zyra.github.io/capacitor-stripe/usage

**Expected behavior**

they should point to : 

https://capacitor-community.github.io/stripe/installation
https://capacitor-community.github.io/stripe/usage

**Comment by clementvp** [comment]
thx you kind sir

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
