### ISSUE TITLE
Have the UI and Words of paymentSheet in French

### ISSUE THREAD

**Issue by darmoor** [capacitor-community/stripe#181]
**Platform**

- [ *] Web
- [ *] iOS
- [ *] Android

**Describe the bug**
I Test a french devices (iphone, android et computer) and the UI of the stripe payment sheet is always in english.
Is there a way to have a french UI? or to translate the words?

**To Reproduce**
Use on french device

**Expected behavior**
The UI and words appear to be in french

**Screenshots**

Thank you for your answers
Quentin

**Comment by rdlabo** [comment]
@darmoor 
iOS) Language is submit from device settings or support info.plist settings:

```info.plist:
<key>CFBundleAllowMixedLocalizations</key>
<string>true</string>
<key>CFBundleLocalizations</key>
<array>
    <string>en</string>
    <string>es</string>
</array>
```

Android) Language is submit from device settings:
https://developer.android.com/guide/topics/resources/localization

Web: French is not supported yet. Please create pull request to https://github.com/stripe-elements/stripe-elements/blob/main/src/utils/i18n.ts

Thanks.

**Comment by rdlabo** [comment]
Has this problem been resolved? No action taken, so this Issue is closed. If you continue to have problems, please create a new Issue.
