### ISSUE TITLE
Use Card Saved with Setup Intent for Later Payment

### ISSUE THREAD

**Issue by briangitrepo** [capacitor-community/stripe#189]
I am using this plugin for my Ionic Capacitor App meant for iOS and Andrdoid. So far I have been able to succesfully save a customer's card to their stripe customer account using createPaymentFlow with a Setup Intent. 

The idea is that a user will enter their credit card info when they register but not actually process a payment until later. How can I use the stored credit card to process a payment later without the user having to enter again their credit card information.

Should I use createPaymentSheet or createPaymentFlow? And how do I tell those methods to use the existing payment method stored for the stripe customer?

**Comment by rdlabo** [comment]
@briangitrepo Thanks for using this plugin, and feedback.
At later payment, we may be able to implements only api implement:
https://stripe.com/docs/saving-cards#saving-credit-card-details-for-later

If you have customer account and saving card information, you don't need this plugin. please try this. Thanks.

**Comment by rdlabo** [comment]
Stripe doesn't provide UI that  select saved credit card UI. So you should provide select saved credit card UI, like amazon:
<img width="341" alt="スクリーンショット 2022-06-10 午前9 20 24" src="https://user-images.githubusercontent.com/9690024/172966094-d365b818-cff5-47aa-bc6b-980ed587e144.png">
 
Thanks.

**Comment by briangitrepo** [comment]
Thanks for the feedback, I found another way to do it.

**Comment by paweuz** [comment]
> Thanks for the feedback, I found another way to do it.

Hi @briangitrepo Could you please share a solution you used? I'm using saved card ID when creating intent on server-side but Stripe plugin / SDK ignores it and pre-selects default card for that customer.

**Comment by indraraj26** [comment]
> Thanks for the feedback, I found another way to do it.

Can you share your way, I did it with setup intent but I do not get the option save card checkbox
