### ISSUE TITLE
On IOS  `confirmPaymentIntent` doesn't return a response.

### ISSUE THREAD

**Issue by syshex** [capacitor-community/stripe#19]
**Describe the bug**

On IOS . `confirmPaymentIntent` doesn't return a response.

**To Reproduce**

```
const resultStripe = await this.$stripe.confirmPaymentIntent({
                        clientSecret: this.client_secret,
                        card: {
                            number: this.cc,
                            exp_month: this.valid_month,
                            exp_year: this.valid_year,
                            cvc: this.post,
                        },
                        redirectUrl: 'https://app.myapp.com', // Required for Android
                    })

console.log('RESULT IS : ' + JSON.stringify(resultStripe) )
```
On android returns a valid json response, with the PI id, etc .

On IOs  the printed result is :      RESULT IS: {}

**Expected behavior**

The same thing as Android. Return a valid JSON object with the details of the confirmation.

**Comment by HardikDG** [comment]
I am also having the same issue. 
Do you find any solution for the same?

**Comment by syshex** [comment]
> I am also having the same issue.
> Do you find any solution for the same?

There is no solution unless you want to change the code of this project. 

The code for the IOS version does not return the response object. Shouldn't be too hard to change.
