### ISSUE TITLE
Google pay is not working on react android demo code

### ISSUE THREAD

**Issue by mostafa3ly** [capacitor-community/stripe#190]
**Platform**

- [ ] Android

**Describe the bug**
Google pay is not working on react android demo code. it logs Not implemented on device on the **react** android demo code

**Comment by rdlabo** [comment]
@mostafa3ly  Thanks for issue.

This was CapacitorStripeProvider's bug. I fixed and released v3.8.2. Please test it.
https://github.com/capacitor-community/stripe/commit/a8ef5f4452321b90b1190f51ac104f42f9fb46ef

Thanks.

**Comment by rdlabo** [comment]
@mostafa3ly Did you run `npx cap update` ? In my device, no problem to run.

**Comment by rdlabo** [comment]
Yes, I tested on react-demo. Now, work with no problem.
Can Google Pay work on your device?

**Comment by mostafa3ly** [comment]
@rdlabo 
yes Google pay is working on my device and i tested it on your demo hosting for when on mobile google chrome browser and it working fine. [](https://capacitor-community-stripe.netlify.app/tabs/tab1)

i tried your plugin on 4 phones and all of them give the same issue.

**Comment by rdlabo** [comment]
I put the word "React" in the title of the Demo to make sure I check it with React-Android. It is indeed working.

![S__12345346](https://user-images.githubusercontent.com/9690024/180121440-b62e1589-7f97-4923-b9f3-338da8d40379.jpg)
![S__12345348](https://user-images.githubusercontent.com/9690024/180121452-5da54f6d-dc66-470f-9781-7ce017c1ffa0.jpg)

Are you sure you run `npm install`?  Make sure the package version of `demo/react/node_modules/@capacitor-community/stripe/package.json` is `3.8.2-0` or higher.

**Comment by rdlabo** [comment]
This Issue will be closed because it has not been updated for a long time. If you encounter similar problems, please start a new Issue.
