### ISSUE TITLE
Detect if the payment flow has been closed

### ISSUE THREAD

**Issue by cyrilfr** [capacitor-community/stripe#192]
When you call `Stripe.presentPaymentFlow()` it opens a closable modal sheet. Unfortunately, the return of this function is inconsistent as it's not able to distinguish between the modal sheet being closed or a credit card being selected.
Actually if you close it with the cross, you get the `cardNumber` of the default selected credit card. This is not what's expected.

A solution would be to set `cardNumber` to `null` if the modal sheet has been closed or add an extra property to mention the actual behavior like with `ion-modal`.

**Comment by cyrilfr** [comment]
The `PaymentFlowEventsEnum.Completed` event is triggered even after a cancel.

**Comment by rdlabo** [comment]
Please use issue format. I can't know where platform you talk about.

**Comment by giuseeFG** [comment]
this issue is still open!
do you have any update on this?
