### ISSUE TITLE
CapacitorStripeProvider for Angular

### ISSUE THREAD

**Issue by dodomui** [capacitor-community/stripe#194]
**Describe the solution you'd like**
Would like to implement Stripe with different publishkey depends on currency as we having multi national stripe account.
CapacitorStripeProvider seem can fit my requirement but I only find the implementation for React but no angular version.
Any possible to have this work on angular? Thanks

**Comment by rdlabo** [comment]
No, CapacitorStripeProvider is use React hooks. So can't work on Angular.
