### ISSUE TITLE
unable to start the stripe gateway 

### ISSUE THREAD

**Issue by Aksoom-Hussain** [capacitor-community/stripe#195]
**Platform**

- [x] Web
- [ ] iOS
- [x] Android

**Describe the bug**

 Unable to find a Capacitor plugin to handle requestCode an android 
```
D/TestOverScroll: getScaledOverscrollDistance: b
D/Capacitor: Unable to find a Capacitor plugin to handle requestCode, trying Cordova plugins 425177417
V/Capacitor/StripePlugin: Notifying listeners for event paymentSheetFailed
D/Capacitor/StripePlugin: No listeners found for event paymentSheetFailed
V/Capacitor/StripePlugin: Notifying listeners for event paymentSheetFailed
D/Capacitor/StripePlugin: No listeners found for event paymentSheetFailed
D/Capacitor/AppPlugin: Firing change: true
V/Capacitor/AppPlugin: Notifying listeners for event appStateChange
D/Capacitor/AppPlugin: No listeners found for event appStateChange
D/Capacitor: App resumed
```

**To Reproduce**
using these 2 function in vue.js nuxt 3 
1 initializing the listener and placing the keys 
2 calling the payment sheet crashing the app
3 in web it give error 

![image](https://user-images.githubusercontent.com/8469844/179458048-1243ce81-d21d-4fe5-a039-a46e5eca047c.png)

```

async function startStripe() {
  await store
    .getStripe(route.params.id, 0)
    .then(async () => {
        Stripe.initialize({
    publishableKey: user.stripe_publishable_key,
  });
      // prepare PaymentSheet with CreatePaymentSheetOption.
      console.log(user.stripe_publishable_key);
      console.log(stripe.value.customer);
        Stripe.addListener(PaymentSheetEventsEnum.Completed, () => {
          console.log('PaymentSheetEventsEnum.Completed');
        });
      await Stripe.createPaymentSheet({
        paymentIntentClientSecret: stripe.value.paymentIntent,
        customerId: stripe.value.customer,
        customerEphemeralKeySecret: stripe.value.ephemeralKey,
      }).then((result) => {
        console.log(result);
      }).catch((err) => {
        console.log(result);
      });
    })
    .catch((err) => {
      console.log(err);
    });
}
async function startgate() {
        // present PaymentSheet and get result.
      await Stripe.presentPaymentSheet().then((result) => {
      console.log(result);
      if (result.paymentResult === PaymentSheetEventsEnum.Completed) {
        console.log(result);
        //await store.stripe(route.params.id,0)
      }
      }).catch((err) => {
        console.log(err);
      });
}
```

**Expected behavior**
unable to start the stripe gateway

**Comment by rdlabo** [comment]
@Aksoom-Hussain  Thanks for issue.  Where is `console.log` that `undefined` displayed?

I suggest you `console.log(["where's log", result]);` . Thanks.

**Comment by Aksoom-Hussain** [comment]
the undefined log come after 
```
await Stripe.createPaymentSheet()
```

the function is not return so it show undefined

**Comment by rdlabo** [comment]
@Aksoom-Hussain `createPaymentSheet` 's `then` ? or `catch` ?
 In many cases, the back-end implementation is the problem (e.g., API keys do not match)

**Comment by Aksoom-Hussain** [comment]
tried on beforemounted() function 

![image](https://user-images.githubusercontent.com/8469844/179704034-0b480824-cbc9-4dc4-aef3-1b36e258cd77.png)

getting this error in vue.js 3 nuxt 3

**Comment by rdlabo** [comment]
OK, I see. It seems `@stripe-elements` 's lazy load and SSG/SSR issue. ( Not this plugin ).

**Comment by Aksoom-Hussain** [comment]
yes stripe elements is installed and in node_module

**Comment by rdlabo** [comment]
@Aksoom-Hussain Please read https://github.com/capacitor-community/stripe/blob/master/src/web.ts#L47-L83 .

1. console log `Stripe` object. 
2. check `stripe-payment-sheet` in body.

However, if you suffer from this, perhaps you should build it yourself at https://stripe.com/docs/payments/elements instead of `@stripe-elements` on web.

**Comment by rdlabo** [comment]
Wait...

```ts
  await store
    .getStripe(route.params.id, 0)
    .then(async () => {
        Stripe.initialize({
    publishableKey: user.stripe_publishable_key,
  });
```

This is not await Stripe.initialize. Why `Stripe.initialize` run into then?

```ts
await store.getStripe(route.params.id, 0);
await Stripe.initialize({
    publishableKey: user.stripe_publishable_key,
});
```

**Comment by Aksoom-Hussain** [comment]
the first await is for the API call then it initialize the stripe

**Comment by rdlabo** [comment]
if `stripe objects is always get undefine` is true, can't run `Stripe.initialize` .

**Comment by Aksoom-Hussain** [comment]
yes that only case for the web android is working fine 

the stripe initialize get this error in web 

 
![image](https://user-images.githubusercontent.com/8469844/179726046-58fc1a43-aacc-4c61-835d-8be3017c796c.png)

**Comment by rdlabo** [comment]
https://github.com/ionic-team/stencil/issues/3195 help you?

This is not plugin issue. I can't help you.

**Comment by Aksoom-Hussain** [comment]
ok let me check

**Comment by rdlabo** [comment]
Sorry I can't help you. A solution might be to not bundle them in vite and use script tags for loading @stripe-elements...

**Comment by Aksoom-Hussain** [comment]
https://stenciljs.com/docs/vue

is it possible to make your library bundle Vue compatible as stencil also have it, that will help in future scope

**Comment by rdlabo** [comment]
> is it possible to make your library bundle Vue compatible as stencil also have it,

Can't. This is not problem about @capacitor-community/stripe.
