### ISSUE TITLE
Error: "Stripe" plugin is not implemented on ios

### ISSUE THREAD

**Issue by aviral282** [capacitor-community/stripe#197]
Hello Everyone,

I am  using the plugin to take one-time payments from the customer, the checkout is working fine on android and the web but giving an error on the iOS app built with capacitor

> [error] - ERROR Error: Uncaught (in promise): Error: "Stripe" plugin is not implemented on ios
> s@capacitor://localhost/main.5024bff7c5c0584d42a9.js:1:577436

Error from Xcode : 

![Screenshot 2022-07-19 at 14 48 54](https://user-images.githubusercontent.com/27973847/179772026-ca4014bb-df08-4a08-a7bc-964196527f2d.png)

The app is running fine on the web and android. no problem with ephemeral key or payment intent I think.

![Screenshot 2022-07-19 at 14 50 52](https://user-images.githubusercontent.com/27973847/179772552-8ebde50a-da73-4a72-9f40-c8040f6eff6b.png)

Do you have any idea what that could be ?

Thank you

**Comment by rdlabo** [comment]
Did you run `npx cap update ios` ?

**Comment by rdlabo** [comment]
@aviral282 Plugin has pod dependency:
https://github.com/capacitor-community/stripe/blob/master/CapacitorCommunityStripe.podspec#L16
https://github.com/capacitor-community/stripe/blob/master/ios/Podfile#L8

Please try to run:

1. `npx cap update ios`
2. `cd ios/App`
3. `pod update`

**Comment by aviral282** [comment]
Hello @rdlabo,

I tried and implemented the stripe in the pod file and updated it
![pod](https://user-images.githubusercontent.com/27973847/180197193-47cc193c-0810-486d-878a-65fa9d2e6f47.jpeg)


This is my profile
![podlock](https://user-images.githubusercontent.com/27973847/180197276-20d9e454-7226-4b43-9bba-7d10d4b3d34a.jpeg)
.lock validating the stripe installed successfully.

But still, the app is not able to find the stripe plugin.

Am i missing any configurations in Xcode or app store connect to enable the stripe in the app?
I have not issued any permission to the app.

**Comment by rdlabo** [comment]
Mumumu... I can't understand why.
Please clone this repository, and try angular-demo:
https://github.com/capacitor-community/stripe/tree/master/demo/angular


First, try it in an environment that works reliably.

**Comment by AdiAditya0** [comment]
Hey @aviral282 ,
After looking at your podfile, it seems CapacitorCommunityStripe dependency has not been added.
Can you please check the Stripe dependency path in the node_modules and add it in the podfile and try pod install?

Something like this
<img width="580" alt="Screenshot 2022-07-22 at 12 14 20 AM" src="https://user-images.githubusercontent.com/31439875/180290568-81411b93-2b7c-4307-b76b-8876c0c50d3d.png">

Hope it helps

**Comment by aviral282** [comment]
@AdiAditya0 , Hello Aditya.
 
 Thanks a million, it works now.
 I was missing the same reference for the 'CommunityStripe Plugin', I referenced it now. Works alright.
 
 @rdlabo I wonder why the application was not able to pick up the reference automatically.
 
 Thanks for the help.

**Comment by rdlabo** [comment]
@aviral282 I'm glad you got it sorted out!
Did you use this plugin for production? If yes, please tell us what app. This help development this plugin.

👉 https://github.com/capacitor-community/stripe/issues/145

Thanks.
