### ISSUE TITLE
Usage on web for dev

### ISSUE THREAD

**Issue by NikolaStanisavljevic** [capacitor-community/stripe#20]
I am trying to use while on web localhost but whichever Stripe method i call i get this error : 
`Stripe does not have web implementation.`

I expected to be functional on web for dev purpose, am i missing something or i would have to build app to test it?

 - OS: Linux
 - Browser Chrome
 - Version 1.0.0-beta.4

**Comment by HardikDG** [comment]
I am having the same issue. Did you find any solution for this?

**Comment by NikolaStanisavljevic** [comment]
@HardikDG Not with this lib. Since i was using Ionic with React, [react-stripe](https://github.com/stripe/react-stripe-js) lib worked form me on web and mobile.

**Comment by HardikDG** [comment]
Thanks for your quick response.
I am also using an ionic-react application. I will check the above library. @NikolaStanisavljevic  This library works well in IOS/Android apps also? 
In my past experience, they were not allowing js payment library in the mobile apps

**Comment by NikolaStanisavljevic** [comment]
Your welcome.
I am not sure for android apps, because i build this app only for apple devices. But can confirm it will work on IOS/web
