### ISSUE TITLE
How to see payment flow failed reason

### ISSUE THREAD

**Issue by briangitrepo** [capacitor-community/stripe#203]
**Platform**

- [X] iOS
- [X] Android

**Describe the bug**

I have set up the listener Stripe.addListener(PaymentFlowEventsEnum.Failed, () => {
      console.log("PaymentFlowEventsEnum.Failed");
    });

But I am wondering if there is a way to get the actual error message for why the payment flow failed. I can see it in the native log but I want to access the actual error message in the typescript file. Is this possible?

**Comment by rdlabo** [comment]
Hi, thanks for issue.

You are right. I add method `string` return, and some update:
https://github.com/capacitor-community/stripe/commit/d0daa9f9d99fd5aabdde54aae60971344c5f3004

Note, however, that this is a change from Capacitor4.

**Comment by rdlabo** [comment]
This Issue will be closed because it has not been updated for a long time. If you encounter similar problems, please start a new Issue.
