### ISSUE TITLE
PaymentSheet Google Pay button is no longer compliant with brand guidelines

### ISSUE THREAD

**Issue by sjthfm** [capacitor-community/stripe#206]
**Is your feature request related to a problem? Please describe.**
Integration will not be approved because the google pay button does not meet Google's brand guidelines. This appears to be the case for Google Pay Button PaymentSheet and standalone Google Pay Button

**Describe the solution you'd like**
New brand guidelines are here: https://developers.google.com/pay/api/android/guides/brand-guidelines#style

![image](https://user-images.githubusercontent.com/25349404/185467242-5927c49a-890b-4bf4-aab4-0bce160c6058.png)

**Comment by rdlabo** [comment]
This plugin is just a wrapper of https://github.com/stripe/stripe-android

So please create issue on https://github.com/stripe/stripe-android/issues
Thanks.

**Comment by rdlabo** [comment]
This Issue will be closed because it has not been updated for a long time. If you encounter similar problems, please start a new Issue.

**Comment by rdlabo** [comment]
@sjthfm I created version supporting stripe-android@20.19.0:
https://github.com/capacitor-community/stripe/tree/feat/target_33#this-is-pre-release-branch

But this require to change `android/variables.gradle`.This may affect other plugins.
@david-nibw  Can you try?
