### ISSUE TITLE
Question: capacitor stripe or cordova stripe

### ISSUE THREAD

**Issue by DwieDima** [capacitor-community/stripe#21]
Currently I want to implement an app based on e-scooter sharing (scann QR code -> pay for amount of minutes -> use device).
I am using latest ionic version with capacitor 2.4.0.
Now I am not sure which plugin to use for stripe.
You offer one for cordova and capacitor.
The cordova plugin has many issues and the master was last updated a year ago. Furthermore there is no promise wrapper for the v2 branch which the capacitor plugin has.

I have a few questions about that:

- Is the cordova plugin compatible with capacitor?
- Is the capacitor plugin production ready?
- will you continue to support the cordova plugin or will it be replaced by capacitor in future?
- which plugin should I use for my project (cordova/capacitor)?

My requirements for the project are:
- payment with Google Pay and Apple Pay
- the payment should be done the new way (intents), not token based
- (optional) pay with credit card without Apple Pay / Google Pay

I am currently not very familiar with the payment procedure. I hope it is ok to ask the question here.
Thanks a lot in advance!

**Comment by ihadeed** [comment]
> Is the cordova plugin compatible with capacitor?

I tested it awhile ago and it worked. The plugin is outdated now.

> Is the capacitor plugin production ready?

For basic payments yes. IIRC it's just missing some client side Payment Methods functionality on iOS and custom sources.

> will you continue to support the cordova plugin or will it be replaced by capacitor in future?

The Cordova plugin isn't a priority at the moment. My focus will be on this project (I plan to update it soon). The Cordova project will be updated by simply copying the code here and replacing a few function calls to make it Cordova compatible. So Cordova will still get updated but it will take longer.

> which plugin should I use for my project (cordova/capacitor)?

Capacitor plugin is more up to date. If you are using Capacitor for your app project, then you should definitely pick Capacitor plugins over Cordova.

**Comment by DwieDima** [comment]
Thanks a lot for clarification!
I'll stick then with the capacitor plugin.

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
