### ISSUE TITLE
Google Pay Showing Unexpected developer error

### ISSUE THREAD

**Issue by devsanuj** [capacitor-community/stripe#212]
**Platform**

- [Android

**Describe the bug**
Tried the demo angular/ionic version in which Google pay is working fine after creating the ionic android-debug.apk. But now I'm using the same plugin in my existing app which has a long list of a pre-existing plugin . After createGooglePay and on presentGooglePay I'm getting `Unexpected developer error, please try again later` instead of the Google Pay screen to appear.  I myself tried a lot to fix the issue but unfortunately no luck yet. 

I believe any of the preexisting plugins create conflict with capacitor-community/stripe. So if  any developer had any idea about this issue then kindly reply back.

Thanks In Advance!

**To Reproduce**
Please check the error screenshot & list of existing plugins that are currently in use.

**Expected behavior**
Google pay bottom dialog box should appear the same as Demo ionic app. But instead of that Unexpected developer error, please try again later appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/90412930/192115772-28fe249f-d322-4ee9-a9cf-faa01736c449.png)
![image](https://user-images.githubusercontent.com/90412930/192115750-bd793ef1-8d2b-43ff-be5a-f0e803771583.png)

**Additional context**

**Comment by SolutionPr** [comment]
Hello Team , Any updates on this ticket ?

**Comment by devsanuj** [comment]
Hello Team , Any updates on this issue ?

**Comment by rdlabo** [comment]
Issue is closed due to lack of information updates. Thanks.
