### ISSUE TITLE
Stripe web stuck in fallback when upgrading to ^4.0.0

### ISSUE THREAD

**Issue by floppydisken** [capacitor-community/stripe#213]
**Platform**
- [x] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
After upgrading to v4.0.0+ the CapacitorStripeProvider gets stuck in fallback mode.

**To Reproduce**
1. Upgrade /demos/react project to v4 of the plugin with the accompanying upgrade to the @capacitor/* plugins to v4
2. `npm run start`
3. Open browser and observe the neverending "Loading..."

**Expected behavior**
To properly initialize the provider for the web project.

**Comment by wtorsi** [comment]
The same, any solution?

**Comment by wtorsi** [comment]
The problem comes from `customElements.whenDefined` and the probably solution is here
https://github.com/webcomponents/polyfills/pull/447

**Comment by floppydisken** [comment]
> The problem comes from `customElements.whenDefined` and probably the solution is here [webcomponents/polyfills#447](https://github.com/webcomponents/polyfills/pull/447)

I didn't find a solution. Did you test the polyfill?

I tested two things:
1. Run a `cusomElements.whenDefined("stripe-payment-sheet")` in the browser to test if it resolves if the custom element is already defined. This worked fine.
2. Create a production build and import the polyfill before the app script.

I had no luck with any solution.

**Comment by phal0r** [comment]
I experienced the same problem and it is bug of this plugin. See this line: https://github.com/capacitor-community/stripe/blob/master/src/react/provider.tsx#L31

It creates a Promise, but never resolves, when web platform is detected.

if you change this
```
new Promise<void>(resolve => Capacitor.isNativePlatform() ? resolve() : defineCustomElements()).then(() => {...
```

to this:
```
let prom = Capacitor.isNativePlatform() ? Promise.resolve() : defineCustomElements()
prom.then(() => { ....
```
it starts working again.

**Comment by AAmeriyan** [comment]
Solved , by adding PWA element 
https://stripe.capacitorjs.jp/docs/angular/
