### ISSUE TITLE
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### ISSUE THREAD

**Issue by jadsy2107** [capacitor-community/stripe#215]
Android

- [ good] Web
- [ good] iOS
- [fails build ] Android

Building works | ionic cap build ios 
building fails with android | ionic cap build android

**To Reproduce**
1. Build in android studio 

The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':capacitor-community-stripe' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

**Comment by jadsy2107** [comment]
Don't like this but I'm doing for now, changes my node_modules/@capacitor-community/stripe/android/build.gradle
from:
```
buildscript {
    ext.kotlin_version = '1.6.0'

```
to:
```
buildscript {
    ext.kotlin_version = '1.6.20'
```

**Comment by rdlabo** [comment]
Thanks for issue. Next version, kotlin_version is be 1.7!

**Comment by jadsy2107** [comment]
> Thanks for issue. Next version, kotlin_version is be 1.7!

Thanks
