### ISSUE TITLE
I can't try the react demo, I am tr

### ISSUE THREAD

**Issue by jacobozonana** [capacitor-community/stripe#217]
**Platform**

- [x] Web
- [x] iOS
- [x] Android

**Describe the bug**
I'm trying to implement stripe in my ionic app, but it can't start the react demo, it stays in endless "Loading...", do you have any guide or idea to be able to try?

Do I need to have the server on?

A tutorial would be awesome

**To Reproduce**
1. Go to 'stripe/demo/react'
2. npm install
3. npm start

**Expected behavior**
I hope to be able to run locally the demo you have online at https://capacitor-community-stripe.netlify.app/tabs/tab1

**Comment by rdlabo** [comment]
@jacobozonana  Sorry for the delay, thanks for the Issue.

This is odd because it works on my environment. Do you see any error messages in the developer tools console?

**Comment by hamza-gfl** [comment]
Hello, @rdlabo I am also facing the same issue with the react demo. I have even replaced the publishable key with my own. But it's still not showing only "Loading...". But when I installed the package on my project and tried running it worked. So don't know why only the demo is not working. There are no errors in console.

**Comment by rdlabo** [comment]
Sorry for the late reply. This issue has already been resolved at https://github.com/capacitor-community/stripe/commit/087240425632f1d189623db1c5e12e29077d29f2. Thanks!
