### ISSUE TITLE
Prevent user from removing the last credit card

### ISSUE THREAD

**Issue by Prakort** [capacitor-community/stripe#218]
**Is your feature request related to a problem? Please describe.**
User can remove all credit cards from the payment flow and the default payment method is detached from the user (Stripe customer). Is this intended feature?

**Describe the solution you'd like**
I would like to have an optional parameter to restrict user from removing the last credit card in the payment flow.

**Comment by dalanmiller** [comment]
>  I would like to have an optional parameter to restrict user from removing the last credit card in the payment flow.

What is the thinking around obliging them to keep a single payment method? What if that payment method is also expired?

**Comment by Prakort** [comment]
@dalanmiller

`What is the thinking around obliging them to keep a single payment method?` My thought process that I want something similar to the demo for the customer management https://stripe.com/docs/customer-management where the user cannot remove a payment method when there is an active subscription. 

`What if that payment method is also expired? `  It definitely needs to be handled by the server when the payment fails. I could see that when the user removes all cards, it has to be handled by the server too.
