### ISSUE TITLE
Stripe Apple Pay not found

### ISSUE THREAD

**Issue by Aksoom-Hussain** [capacitor-community/stripe#227]
**Platform**

- [ ] Web
- [x] iOS
- [ ] Android

Unable to find Stripe apple pay 23.0.0 in 4.1.0 version

issue due to the following commit had to get back in 4.0.0 ver
https://github.com/capacitor-community/stripe/commit/91c10fb6e6ef2a0fda255006338cce827b1f284d

**Comment by rdlabo** [comment]
@Aksoom-Hussain Did you try to run `npx cap update` , or `pod install` and `pod update` command?
This is a Pod issue, not a plugin issue.

**Comment by Aksoom-Hussain** [comment]
i update to the latest version now it work fine, as for now i face small DX issue in iOS every build i need to select the certificates of 6 stripe package which is really irritation earlier it was 4, is there any hack to this repetitive step
