### ISSUE TITLE
addListener events get duplicated.

### ISSUE THREAD

**Issue by anthonnyc2** [capacitor-community/stripe#228]
**Platform**

- [x] iOS
- [x] Android

**Describe the bug**
I'm having an issue with the listeners... Each time I visit a page the listeners get duplicated. So, I was wondering how to manage that.?
 I looked in the documentation but just see addListener functions. 
 
 How should I remove the addListener callbacks?

**Comment by rdlabo** [comment]
This is capacitor's issue. Please `remove` .
https://capacitorjs.com/docs/plugins/ios#plugin-events
