### ISSUE TITLE
save user credit card without payment

### ISSUE THREAD

**Issue by jpissis** [capacitor-community/stripe#229]
If a user use a coupon that offer free period, your module doesn't work because "PaymentSheet" and "PaymentFlow"  require a Stripe payment intent and the Stripe payment intent require an amount > 0,50€

So is it possible to implement credit card API to create a card for futur usage without payment ?

Many thanks

**Comment by Prakort** [comment]
@jpissis You can use the setup intent flow instead of payment intent: https://stripe.com/docs/payments/setup-intents

**Comment by rdlabo** [comment]
Thanks for issue. Yes, @Prakort is right. @jpissis please try to use setup intent.
