### ISSUE TITLE
Styles and Themes

### ISSUE THREAD

**Issue by co-dax** [capacitor-community/stripe#237]
Is possible to apply css styles to elements?

**Comment by Prakort** [comment]
@co-dax By react or angular, I dont think so.

**Comment by co-dax** [comment]
Thanks @Prakort!

**Comment by rdlabo** [comment]
In the browser, @stripe-elements/stripe-elements can change styles and themes by css.But in the ios or android, paymentSheet, or else is work native layer. so can't.

Thanks.

**Comment by co-dax** [comment]
Thanks @rdlabo.
