### ISSUE TITLE
Question: How to get the billing details out of Apple Pay / Google Pay?

### ISSUE THREAD

**Issue by mariusbolik** [capacitor-community/stripe#243]
Hello, thank you for the awesome Plugin!
Is there a way to receive the billing information after payment, so I can create an account for the user on my backend?

**Comment by mariusbolik** [comment]
The data is incomplete. Address and name are missing. The plugin [capacitor-plugin-applepay](https://github.com/fresha/capacitor-plugin-applepay) also return the full address. So it should be possible for the stripe plugin.

<img src="https://user-images.githubusercontent.com/39862171/207669758-bd1e5a06-1955-4227-a1f7-1fed5e809d7e.jpg" height="500px">

**Comment by rdlabo** [comment]
@mariusbolik Thanks for issue. You can set field at Apple Pay:

We prepare `requiredShippingContactFields` for get user information. Please pass by method of CreateApplePayOption.
https://github.com/capacitor-community/stripe/blob/master/ios/Plugin/ApplePay/ApplePayExecutor.swift#L49-L67

Please try this.

But not implement to get Google Pay's shippingAddress. I shall challenge you to implement it in the near future.
Thanks.

**Comment by rdlabo** [comment]
Reference: https://developers.google.com/pay/api/web/guides/tutorial?hl=ja#load

**Comment by EdByrnee** [comment]
> The data is incomplete. Address and name are missing. The plugin [capacitor-plugin-applepay](https://github.com/fresha/capacitor-plugin-applepay) also return the full address. So it should be possible for the stripe plugin.
> 
> <img alt="" height="500px" src="https://user-images.githubusercontent.com/39862171/207670902-2c6acc38-989d-45b7-b9d3-85e9e6086871.jpg">

Did you manage to find a solution for this?

Are we subscribing to the correct event? Are the shipping details only available after Authorization (apple pay)?

**Comment by krisloekkegaard** [comment]
I created PR #280 which should solve this. It's working for our use case (we get the email address and phone number from Google Pay users on Android), but let me know if anyone has issues using it.  We are running against a fork, but would love to get back on the official package if this is merged 🤞

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. Please create a new Issue if necessary.
