### ISSUE TITLE
PaymentSheet Google Pay button is no longer compliant with brand guidelines

### ISSUE THREAD

**Issue by david-nibw** [capacitor-community/stripe#254]
Is your feature request related to a problem? Please describe.
Integration will not be approved because the google pay button does not meet Google's brand guidelines. This appears to be the case for Google Pay Button PaymentSheet and standalone Google Pay Button

Describe the solution you'd like
New brand guidelines are here: https://developers.google.com/pay/api/android/guides/brand-guidelines#style

**Screenshots**
![image](https://user-images.githubusercontent.com/84137464/212122191-c7fffc87-0be1-4f9b-b2be-930f9314a4ee.png)

**Comment by rdlabo** [comment]
Thanks issue.
I created version supporting stripe-android@20.19.0:
https://github.com/capacitor-community/stripe/tree/feat/target_33#this-is-pre-release-branch

But this require to change `android/variables.gradle`.This may affect other plugins.
@david-nibw  Can you try?

**Comment by xras-dev** [comment]
it works but there is a delay of 15 seconds when showing the payment sheet. i dont know if its only in my device.
![screenshot](https://user-images.githubusercontent.com/65831939/214574554-3d2ae8a9-c2e4-4706-9c67-c265ec62e1df.png)

**Comment by rdlabo** [comment]
I too can confirm that it appears late. This does not occur with v20.17.0, but starting with v20.18.0🤔

**Comment by rdlabo** [comment]
v20.11 - 17: https://www.dropbox.com/s/v4mo4lo9h14nngt/screen-20230126-122000.mp4?dl=0
v20.18 - 19 : https://www.dropbox.com/s/k14ijse0mzykues/screen-20230126-121507.mp4?dl=0

**Comment by rdlabo** [comment]
@xras-dev v4.1.2-1 is released. this use stripe-android@20.17.0. Please try.

**Comment by xras-dev** [comment]
v4.1.2-1 working perfect but v4.1.2 is still using stipe v20.11 
<img width="723" alt="Captura de pantalla 2023-01-26 a las 9 50 45" src="https://user-images.githubusercontent.com/65831939/214797088-7335ab6f-7e53-4de1-9224-542eff3c543e.png">

**Comment by rdlabo** [comment]
That's right. I'm wonder if it is mandatory to give the compileSdkVersion and targetSdkVersion of the project for the plugin. So this will be operated with the `next` tag for the time being.

**Comment by xras-dev** [comment]
ok, good work!
