### ISSUE TITLE
STPApplePayContext is failed

### ISSUE THREAD

**Issue by EdByrnee** [capacitor-community/stripe#255]
I'm attempting to showApplePay but I'm getting the following error:

**STPApplePayContext is failed**

Should there be more information for this log line? It doesn't give any indication as to what is incorrectly configured

**Comment by EdByrnee** [comment]
Does anyone have any ideas on how I can see more detailed logging so I can try to debug the issue?

**Comment by EdByrnee** [comment]
I'm not sure how I can move forward with this. Is there any option available to get more detail logging than simply **STPApplePayContext is failed**

**Comment by josuelmm** [comment]
Were you able to solve the problem?
