### ISSUE TITLE
Apple pay and google pay is not working 

### ISSUE THREAD

**Issue by orderpointdevsupport2** [capacitor-community/stripe#257]
**Platform**

- [ ] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
hi when we are hitting the api 
Stripe.createGooglePay,
Stripe.presentGooglePay
Stripe.createApplePay
Stripe.presentApplePay

i am getting this kind of error
**APPLE PAY ERROR**
⚡️  [log] - Pay with Apple pay button hits⚡️  To Native ->  Stripe isApplePayAvailable 43995628ERROR MESSAGE:  {"errorMessage":"Can not use on this Device.","message":"Can not use on this Device."}⚡️  [error] - {"errorMessage":"Can not use on this Device.","message":"Can not use on this Device."}⚡️  [log] - dismissed⚡️  To Native ->  Stripe createApplePay 43995629⚡️  TO JS {}⚡️  TO JS undefined⚡️  [log] - ApplePayEventsEnum.Loaded⚡️  To Native ->  Stripe presentApplePay 43995630ERROR MESSAGE:  {"message":"STPApplePayContext is failed","errorMessage":"STPApplePayContext is failed"}⚡️  [error] - {"message":"STPApplePayContext is failed","errorMessage":"STPApplePayContext is failed"}⚡️  [error] - ERROR Error: Uncaught (in promise): Error: STPApplePayContext is failedCapacitorException@capacitor://localhost/vendor.js:3048:10returnResult@user-script:2:709:49@user-script:2:691:29
**GOOGLE PAY ERROR**
VM3:219 result Stripe.isGooglePayAvailable (#5809816)
VM3:227 {message: 'Not implemented on Device.', code: 'UNIMPLEMENTED'}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rdlabo** [comment]
Please check document:

iOS https://stripe.com/docs/apple-pay?locale=ja-JP#merchantid
Android https://developers.google.com/pay/api/android/guides/setup

`Can not use on this Device.` may be right.

**Comment by rdlabo** [comment]
This Issue is closed because the information has not been updated. Thank you.
