### ISSUE TITLE
Confirm payment always catches event Completed, never Failed

### ISSUE THREAD

**Issue by AlesDspot** [capacitor-community/stripe#266]
**Platform**

- [ x] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
Inputing a test card number which fails (4100000000000019)  makes a call to api.stripe.com:
https://api.stripe.com/v1/payment_intents/pi_3MdXWFCyDbRyOrdF01urgsUD/confirm

which returns the correct response:

![image](https://user-images.githubusercontent.com/102789053/220094294-3a2d99c2-3781-4caf-b830-84ec2b2e9ad2.png)

But the confirmPaymentFlow always returns Completed. I cannot seem to catch the event for failed.

Also (not sure if it's related), the Postal code input is disabled and cannot be typed in.

**Expected behavior**
Catch the failed response.

**Comment by Nykz** [comment]
This plugin is not catching the events canceled or failed upon canceling the process or even if the actual card is declined... kindly fix this...

**Comment by AlesDspot** [comment]
I tried even with PaymentSheet, and it also doesn't catch Failed, only Completed

**Comment by rdlabo** [comment]
That's right, because Stripe always returns completed:

https://github.com/capacitor-community/stripe/blob/master/ios/Plugin/PaymentSheet/PaymentSheetExecutor.swift#L81-L83

I think the implementation needs to check separately whether the customer's payment has been successfully completed on the back end.

**Comment by rdlabo** [comment]
This Issue is closed because the information has not been updated. Thank you.

**Comment by Nykz** [comment]
@rdlabo If thats the case then its a big flaw. If the plugin cannot say whether the transaction is completed or not...not throwing proper errors then how will it be detected anywhere... it should pass at least some parameter to track it down...with payment gateways cant take any chance at all... as it involves money
