### ISSUE TITLE
Advantage over @stripe-elements/stripe-elements

### ISSUE THREAD

**Issue by co-dax** [capacitor-community/stripe#267]
What are the advantages of using this plugin over using @stripe-elements/stripe-elements?

**Comment by rdlabo** [comment]
The @capacitor-community/stripe API can be used to make Stripe payments. However, you do not necessarily need to use this.

````
if (Capacitor.isNativePlatform()) {
}
```

There is nothing wrong with branching out and doing your original web implementation with

Thanks.

**Comment by rdlabo** [comment]
This Issue is closed because the information has not been updated. Thank you.
