### ISSUE TITLE
Change UI PaymentSheet popup

### ISSUE THREAD

**Issue by enfix86** [capacitor-community/stripe#269]
I would like to change the popup UI that is shown with the PaymentSheet.
I need it in iOS and Android.
How can i do this? Any API?

Thanks

**Comment by rdlabo** [comment]
@enfix86  I see stripe doesn't prepare popup UI API:
https://stripe.com/docs/payments/accept-a-payment?platform=ios

If you need, you should create custom UI using [STPPaymentCardTextField](https://stripe.dev/stripe-ios/stripe-payments-ui/Classes/STPPaymentCardTextField.html) and [CardInputWidget](https://stripe.dev/stripe-android/payments-core/com.stripe.android.view/-card-input-widget/index.html).

If you create pull request for it, I'd be happy to review it.
Thanks.

**Comment by rdlabo** [comment]
This Issue is closed because the information has not been updated. Thank you.
