### ISSUE TITLE
createPaymentSheet - Failed to construct 'URL': Invalid base URL

### ISSUE THREAD

**Issue by stylianosnicoletti** [capacitor-community/stripe#271]
**Platform**

- [* ] Web
- [* ] iOS
- [ *] Android

**Describe the bug**
Getting the following after calling stripe.createPaymentSheet(...)

 index.js:33 Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at getAssetPath (index.js:33:1)
    at getNamedUrl (icon.js:44:1)
    at getUrl (icon.js:25:1)
    at Icon.mode.loadIcon (icon.js:286:1)
    at icon.js:257:1
    at Icon.mode.waitUntilVisible (icon.js:281:1)
    at Icon.mode.connectedCallback (icon.js:255:1)
    at Icon.mode.connectedCallback (index.js:2420:1)
    at addVnodes (index-a7e5d6fd.js:477:1)
    at patch (index-a7e5d6fd.js:641:1)

**Comment by rdlabo** [comment]
@stylianosnicoletti Thanks for create issue.
Did you try demo application? https://github.com/capacitor-community/stripe/tree/master/demo

We don't know your implementation. Try our demo app or point us to a public repository of your implementation.
Thanks.

**Comment by stylianosnicoletti** [comment]
Hi, thanks for replying..the think is that i want to implement this with my own project, not the demo..

When i use this plugin, a batch of warning messages appear in the console as well as the error i am describing above.

Btw, the flow seems to me working fine, the anoying thing is these messages coming in console, which are directly related to the plugin code if you debug it.

I will probably use the plain react js stipe package instead of this plugin as this seems to be more stable.
