### ISSUE TITLE
Error(Apple Pay / Web): IntegrationError: show() must be called from a user gesture handler

### ISSUE THREAD

**Issue by sangheraajit** [capacitor-community/stripe#272]
**Platform**

- [ ] Web

**Describe the bug**
Error: Uncaught (in promise): IntegrationError: show() must be called from a user gesture handler (such as a click handler,

**To Reproduce**
1. Go to open your demo on the safari browser
2. Click on apple create and then present
3. check the browser console
 Error: Uncaught (in promise): IntegrationError: show() must be called from a user gesture handler (such as a click handler,

**Screenshots**
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/12188266/224536917-41bad10f-d167-48fd-b3f3-46f193786ea6.png">

**Additional context**

**Comment by rdlabo** [comment]
move https://github.com/wpkyoto/stripe-pwa-elements/issues/42
