### ISSUE TITLE
framewrok7 error

### ISSUE THREAD

**Issue by PeraDev7** [capacitor-community/stripe#274]
**Platform**

- [X ] Web
- [X ] iOS
- [X ] Android

**Describe the bug**
When i add the code on my Framework7 x capacitor project, the plugin is not working.
I added with npm and initialized on main.js with : 
`Stripe.addListener(PaymentSheetEventsEnum.Completed, () => {
    console.log('PaymentSheetEventsEnum.Completed');
  });`
But i din't have any log returned.
I'm working on framework7 core

**Comment by rdlabo** [comment]
Sorry, I don't use framework7, so can't support.
This plugin has been verified to work with other frameworks (Angular/React), so first check that the event listeners are set correctly.

**Comment by rdlabo** [comment]
This issue is closed due to lack of activity for a long time. Please start a new Issue if needed.
