### ISSUE TITLE
Not getting option to save cards using paymentflow

### ISSUE THREAD

**Issue by indraraj26** [capacitor-community/stripe#275]
**Platform**

- [ ] Web
- [ ] iOS
- [X] Android

**Describe the bug**
I have configured as you did it in your demo, Still i do not get the option to save cards for future payments. even i ran your demo on my android device.

**To Reproduce**

**Expected behavior**
 
**Screenshots**

**Additional context**
Target sdk 32 and version: 4.1.0

**Comment by rdlabo** [comment]
Thanks for issue. In my hand, the option to save the card is visible. It is the part that shows "今後のrdlaboの支払いのために保存する" in Japanese.

![Screenshot_20230329-171154](https://user-images.githubusercontent.com/9690024/228470046-fe5162d3-e519-40a4-8527-6238d1db7ec0.png)

**Comment by alexskrms** [comment]
For me, it's happening the same. It does not appear as an option.

**Comment by rdlabo** [comment]
It may be a customer token issue. Have you tried demo/angular?

https://github.com/capacitor-community/stripe/tree/master/demo/angular

**Comment by rdlabo** [comment]
This issue is closed due to lack of activity for a long time. Please start a new Issue if needed.
