### ISSUE TITLE
Can't publish on Google Play Store since using the package

### ISSUE THREAD

**Issue by DevForAll-Loic** [capacitor-community/stripe#278]
First, thank's to the community for your work!

**Platform**

- [ ] Web
- [ ] iOS
- [X] Android

**Describe the bug**
We have an App already published in production. We wanted to add feature with Capacitor Stripe Community, and then when we published the new update with the package and feature included, we got refused to be published by Google because Policy Rules not compliant. 

**To Reproduce**
1. Publish an mobile App on google Play Store.
2. Add Capacitor-Community/Stripe to your project.
3. Publish new release to Google Play Store.
4. Get refused by Google. 

**Expected behavior**
Being published on Google Play Store. 

**Screenshots**
Added to the thread.

Using Function:
- [X] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

<img width="681" alt="Capture d’écran 2023-03-27 à 18 07 22" src="https://user-images.githubusercontent.com/54630306/228000266-5f518262-bfc9-4115-a3b2-e650497f7040.png">

**Comment by rdlabo** [comment]
Thanks for issue. capacitor-community/stripe use some user data. Please try to change Google Play Console's Data Safety.

**Comment by smccamley** [comment]
some user data? What user data specifically?

**Comment by rdlabo** [comment]
We cannot answer this question because it depends on which features your application uses. If you need assistance, please contact Stripe.
