### ISSUE TITLE
Tap to pay  in person payments on iPhone

### ISSUE THREAD

**Issue by madmacc** [capacitor-community/stripe#279]
It would be amazing to get this to work with tap to pay on iPhone if this is something that aligns with the plan.
https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay-on-iphone

This would allow a user to tap their card or mobile device on the device with the app to instantly pay using NFC.

My app would use this to take donations for a non profit in person.

**Comment by darinw** [comment]
Is there any plan to add this?

**Comment by rdlabo** [comment]
Thanks. This will require significant work, including package separation, to actually do. We will work on this when we have time, but cannot reveal our plans yet.

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. Please create a new Issue if necessary.

**Comment by Jeff-P** [comment]
Has there been any development on this?
