### ISSUE TITLE
Change package name to com.capacitorjs.community.plugin

### ISSUE THREAD

**Issue by ihadeed** [capacitor-community/stripe#28]
This applies to the Android package only

**Comment by tx-tim** [comment]
@ihadeed Is the current documentation correct, that MainActivity.java should import `ca.zyra.capacitor.stripe.Stripe` and not `com.getcapacitor.community.Stripe` ?  I haven't found a good way to search for available packages by name

**Comment by dwieeb** [comment]
@ihadeed Just as a heads up we may prefer `com.capacitorjs.community.plugin` (we're using `com.capacitorjs.plugin` in our plugins: https://github.com/ionic-team/capacitor-plugins)

**Comment by ihadeed** [comment]
> @ihadeed Is the current documentation correct, that MainActivity.java should import `ca.zyra.capacitor.stripe.Stripe` and not `com.getcapacitor.community.Stripe` ? I haven't found a good way to search for available packages by name

That's correct. The current package name is `ca.zyra.capacitor.stripe.Stripe`

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
