### ISSUE TITLE
Apple Pay is not working on web

### ISSUE THREAD

**Issue by ottojaa** [capacitor-community/stripe#282]
**Platform**

- [x] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
Apple pay is not available on web. 

I'm slightly confused about the current state of this feature, the main github page mentions that Apple Pay is in "beta", but looking at the repo, there's clearly an implementation for web Apple Pay in `web.ts` that was implemented more than a year ago. Demo has "Apple pay" section, which does not seem to present the payment form, regardless of device / browser. Does it not work on any device? Has it worked at some point? At least according to [stripe docs](https://stripe.com/docs/apple-pay), it should work pretty much out of the box in web environment on a newer Iphone / Mac.

Our application is currently web-only, and apple pay support would be very good to have. Google pay on web works very well!

**To Reproduce**
Go to https://capacitor-community-stripe.netlify.app/tabs/demo with Iphone, Latest Safari

Press "create"
Press "present"

Nothing happens.

**Expected behavior**
I expect to be able to use Apple Pay on Mac / Iphone.

Using Function:
- [ ] Payment Sheet / Payment Flow
- [x] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
This is same issue of https://github.com/capacitor-community/stripe/issues/282
Thanks, I will close this to integrate the issue.

**Comment by sir-captainmorgan21** [comment]
@rdlabo you linked to this issue as the same issue

**Comment by ottojaa** [comment]
@rdlabo could you reopen this? I believe it was closed accidentally.
