### ISSUE TITLE
Cocoapods StripeApplePay Error

### ISSUE THREAD

**Issue by razarahil** [capacitor-community/stripe#283]
Whenever I tried to generate the build using cap sync ios, I'm getting this error. 

[!] CocoaPods could not find compatible versions for pod "StripeApplePay":
[capacitor]         In Podfile:
[capacitor]         CapacitorCommunityStripe (from `../../node_modules/@capacitor-community/stripe`) was resolved to 4.2.2, which depends on
[capacitor]         StripeApplePay (= 23.4.0)

I'm using the Stripe Plugin only for the web.

**Comment by ciccilleju** [comment]
you must update your pod repository 
try to run ` pod install --repo-update` and then 
`npx cap sync `

**Comment by rdlabo** [comment]
> you must update your pod repository try to run ` pod install --repo-update` and then `npx cap sync `

This is the solution. This Issue is closed due to lack of progress. Thank you.

**Comment by madmacc** [comment]
> you must update your pod repository try to run ` pod install --repo-update` and then `npx cap sync `

Thanks @ciccilleju this solved the problem.
Just to add this, you need to run this in the yourproject/ios/app directory otherwise you get the error "No 'Podfile' found in the project directory. This was for an Ionic project.
