### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by christ0089** [capacitor-community/stripe#285]
**Is your feature request related to a problem? Please describe.**
What are the consideration for using Capacitor 5 

**Describe the solution you'd like**
Roadmap or tasks to help for supporting Capacitor 5

**Describe alternatives you've considered**
Using the Ngxr/Stripe on App for payment processing

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: GalaMuebles
Product URL : gala-muebles.web.app
Using Function:
- [x] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
Thanks for issue. I released v5.0.0 for Capacitor 5. Please try this:
https://github.com/capacitor-community/stripe/releases/tag/v5.0.1

**Comment by christ0089** [comment]
LGTM! Thankyou
