### ISSUE TITLE
Can't able to enable iDEAL payment method 

### ISSUE THREAD

**Issue by taruneeth** [capacitor-community/stripe#287]
**Platform**

- [ ] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
Seems this package is not supports the iDEAL Payment method

**Screenshots**
![image](https://user-images.githubusercontent.com/125116383/236598352-ae089d53-af01-40e3-8318-1fae3086504e.png)

**Usage Product**
We developing transport related App for NL Clients, Already we developed web app enabled with iDEAL payment method, Now looking for mobile app  

Product Name:  jezsel
Product URL : https://jezsel.nl/
Using Function:
- [ ] Payment Sheet / Payment Flow

**Comment by rdlabo** [comment]
This is same issue: https://github.com/capacitor-community/stripe/issues/88

Currently we do not develop methods for specific countries (from Japan I can not try). We will gladly review your pull requests if you send them to us.
Thanks.
