### ISSUE TITLE
Stripe Identity Not Loading Showing Error There was an unexected error Message

### ISSUE THREAD

**Issue by CharnjeetIotasol** [capacitor-community/stripe#291]
**Platform**

- [ ] Web
- [ ] iOS
- [x] Android

**Describe the bug**
We are facing issue while loading Stipe Identity Screen in mobile app. I have integrate plugin in our project which running on Capacitor 5.0.3. I have got correct verificationId and ephemeralKeySecret from server. Even I have review the log on Stripe site which returning 200 OK. But I am getting screen in mobile **Error*, There was an unexected error -  please try again in a few seconds*

**Expected behavior**
It should open Stripe Identity flow screen.

**Screenshots**
![image](https://github.com/capacitor-community/stripe/assets/7870683/16e4b5ec-8c17-47e6-8ad1-cd029f5ef211)
![image](https://github.com/capacitor-community/stripe/assets/7870683/5e279df4-caf4-4ad9-8c97-b66f15b845d6)
![image](https://github.com/capacitor-community/stripe/assets/7870683/40b5764e-ef7f-425b-a25b-0ba17e830908)
![image](https://github.com/capacitor-community/stripe/assets/7870683/4276b477-7b84-46fc-9928-878bf37749fa)
![image](https://github.com/capacitor-community/stripe/assets/7870683/4d939fd3-cd48-488a-a58f-c30b4bf2cde2)

**Additional context**
URL in Stripe Log:

https://verify.stripe.com/start/test_YWNjdF8xTGhPOHFKb3VLVXJCRWFULF9OdXZPS1F6M1N0VlQ0WWFqMlRycThxdnRWN3pRY1NS0100LqEX7AaL

**Usage Product**
I am using this plug with version: @5.0.1. 

Product Name:  capacitor-community/stripe
Product URL : https://github.com/capacitor-community/stripe@5.0.1
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [x] Identity Verification Sheet

**Comment by hideokamoto-stripe** [comment]
@rdlabo 
FYI.

It seems the issue during handling the Stripe API response.
Possibly we need to take a look at the code for Android.

https://github.com/capacitor-community/stripe/blob/master/android/src/main/java/com/getcapacitor/community/stripe/identityverification/IdentityVerificationSheetExecutor.java

**Comment by hideokamoto-stripe** [comment]
And additionally, we published the new version SDK to each environment (Android: 20.25.2, iOS: 23.8.0).
How about upgrade these SDKs(Android: 20.19.5, iOS: 23.4.0)?

https://github.com/capacitor-community/stripe/blob/master/android/build.gradle#L62-L67
https://github.com/capacitor-community/stripe/blob/master/ios/Podfile#L8-L10

Thanks.

**Comment by CharnjeetIotasol** [comment]
Thanks @hideokamoto-stripe  For quick response.

I have added the latest plugin version i.e  
"@capacitor-community/stripe": "^5.0.1",

Android: 20.19.5, iOS: 23.4.0 are part of plugin 5.0.1, First you have update the version in plugin and release latest version of plugin then we will update the plugin version in our code and will try it.

**Comment by rdlabo** [comment]
Thanks for the Issue. The demo/angular seems to be working fine on my end. @CharnjeetIotasol Please try demo/angular once.

https://github.com/capacitor-community/stripe/tree/master/demo/angular

**Comment by rdlabo** [comment]
This issue is closed due to lack of activity for a long time. Please start a new Issue if needed.
