### ISSUE TITLE
Recurring payment with Apple Pay & Google Pay

### ISSUE THREAD

**Issue by SossenSystems** [capacitor-community/stripe#294]
**Does your function request relate to a problem? Please describe it.**
I am frustrated because I have not found a way to implement Apple Pay and Google Pay as recurring payments.

**Describe the solution you want**.
I would be really happy if recurring payments were possible for Apple and Google Pay, meaning I have a subscription and it is supposed to be debited EUR 10.00 every month.

**Describe the alternatives you have considered**.
The project is great, I would like to solve it with this one, thanks for the opportunity!

**Additional context**
-

**Use product**
I use credit card payments.

Product Name:
Product URL :
Function used:
- [YES] Payment form / payment flow.
- [Desired] Apple Pay
- [Desired] Google Pay
- [NO] Identity verification form

**Comment by rdlabo** [comment]
Thanks for the issue. This is an issue with the way tokens are created in the backend, not with the plugin.

docs: https://support.stripe.com/questions/using-apple-pay-for-recurring-payments?locale=en-US

**Comment by SossenSystems** [comment]
Thanks for your answer. I'm using in the backend:
```
async createSetupIntent(customer: string) {
        const setupIntent = await this.stripe.setupIntents.create({
            customer,
            usage: 'off_session',
        });
        return setupIntent.client_secret;
    };
```
So where i can insert the recurring payment?

**Comment by rdlabo** [comment]
This is not a problem on the plugin side, so please contact Stripe.

**Comment by SossenSystems** [comment]
But can you not show an example of it, how to do it in your code?
