### ISSUE TITLE
On completion, presentPaymentOptions triggers other Capacitor listener events. 

### ISSUE THREAD

**Issue by zyxt** [capacitor-community/stripe#295]
**Platform**

- [ ] Web
- [ ] iOS
- [X ] Android

**Describe the bug**
Working with a payment flow on Android, latest version of this plugin, Capacitor 5.0. flowController.presentPaymentOptions(); executes, and on completion, other listener events that have been registered in capacitor are triggered (for example, App change state).

Using Function:
- [ x] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
https://github.com/capacitor-community/stripe/blob/master/android/src/main/java/com/getcapacitor/community/stripe/paymentflow/PaymentFlowEvent.kt#L3-L12

All of the events used by flowController are located here and do not conflict in name with others.

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. Please create a new Issue if necessary.
