### ISSUE TITLE
Keyboard inaccessible 

### ISSUE THREAD

**Issue by drakedeatonuk** [capacitor-community/stripe#297]
**Platform**

- [ ] Web
- [*] iOS
- [ ] Android

**Describe the bug**
When calling `Stripe.createPaymentSheet` & `Stripe.presentPaymentSheet`, when selecting a country from the country selection picker, if I click directly onto the "Postal Code"/"Zip Code" input beneath of this, then the keyboard closes and it wont reopen until I change back to the previous input and reselect the "Postal Code"/"Zip Code" input again (this is demoed in the video below).

Interestingly, if I do not click on the country selection picker at all, then when I click on the "Postal Code"/"Zip Code" input, the keyboard will stay open (this is demoed at the end of the video below).

**To Reproduce**
1. Open the `Stripe.createPaymentSheet` & `Stripe.presentPaymentSheet` modal
2. Select a country (United Kingdom or United States)
3. Click the "Postal Code"/"Zip Code" input
4. See error: you'll see that the keyboard closes and wont open again.

**Expected behavior**
The keyboard should be open when the user clicks directly on this input after setting a country.

**Screenshots**
The issue can be seen below:
https://github.com/capacitor-community/stripe/assets/41165256/d34218bb-c00d-4d87-a9dd-8666871209fb

**Usage Product**
I'm using the latest version - 5.0.1

**Comment by rdlabo** [comment]
Thanks for the report. This is an issue with the Stripe iOS SDK, not the plugin.

https://github.com/stripe/stripe-ios

Please report it here.

**Comment by drakedeatonuk** [comment]
@rdlabo I raised this as an issue on the stripe-ios repo here: https://github.com/stripe/stripe-ios/issues/2936#issuecomment-1755795591

A fix for this went in on the latest release - any chance  of getting this lib bumped to support the change?

**Comment by rdlabo** [comment]
@drakedeatonuk  I appreciate your excellent contribution and look forward to your continued support. The package including this will be released today as v5.3.0.

**Comment by rdlabo** [comment]
released: https://github.com/capacitor-community/stripe/releases/tag/v5.3.0

**Comment by drakedeatonuk** [comment]
hi @rdlabo - I've tested this with the update and can confirm that the bug has been fixed now. Thanks very much your help & for this very useful library :) 🙏
