### ISSUE TITLE
Cannot install via NPM

### ISSUE THREAD

**Issue by kyleshepherd** [capacitor-community/stripe#30]
**Describe the bug**
I'm not able to install the package via NPM using the command shown in the `README.md`

**To Reproduce**
1. Run `npm i -S @capacitor-community/stripe` in Terminal
2. Receive below output:
```npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@capacitor-community%2fstripe - Not found
npm ERR! 404
npm ERR! 404  '@capacitor-community/stripe@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Expected behavior**
Should install the package, but instead returns an error

**Comment by ihadeed** [comment]
`capacitor-stripe` should work

The updated package `@capacitor-community/stripe` will be published soon.
