### ISSUE TITLE
Inconsistant native Android/iOS version across payment and identity plugin

### ISSUE THREAD

**Issue by ccen-stripe** [capacitor-community/stripe#308]
**Platform**

- [ ] Web
- [x] iOS
- [x] Android

**Describe the bug**
Hi 👋  This is Chen from Stripe's mobile team, I just created [this PR](https://github.com/capacitor-community/stripe/pull/306) on versioning the native SDKs for Identity and find a potential bug across the payment and identity plugins, please see details below - 

Both payment and identity integrate the native Android/iOS SDKs, we need to make sure the versions are the same across both plugins, otherwise for user using both plugins within the same app, it would cause the app failed to build due to conflict version numbers, I would suggest save the iOS/Android version constants somewhere and refer to the constants from respective iOS/Android files

* iOS version(`23.4.0`) in payment: [link](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/payment/CapacitorCommunityStripe.podspec#L16), also please note: [StripeIdentity](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/payment/CapacitorCommunityStripe.podspec#L18C17-L18C31) is not required for payment
* iOS version(`~> 23.4.0`) in Identity: [link](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/identity/CapacitorCommunityStripeIdentity.podspec#L16)
* Android version(`20.28.2`) in payment: [link](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/payment/android/build.gradle#L65C41-L65C41), also please note: [com.stripe:identity](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/payment/android/build.gradle#L71C21-L71C40) is not required for payment
* Android version(`20.28.+`) in Identity: [link](https://github.com/capacitor-community/stripe/blob/23657df36e9208523fb8f983cf1ddd2aa1e08fe2/packages/identity/android/build.gradle#L65)

For reference, here are the links for the version numbers for Stripe's react native SDKs, since payment and identity SDK live in different repos, we can't share the constants, but we always coordinates internally to release compatible versions together.
* Identity react native iOS: [link](https://github.com/stripe/stripe-identity-react-native/blob/a4ea79c31c73ef2ee0a08737ded64d32ece7dbc4/stripe-identity-react-native.podspec#L6)
* Identity react native Android: [link](https://github.com/stripe/stripe-identity-react-native/blob/a4ea79c31c73ef2ee0a08737ded64d32ece7dbc4/android/gradle.properties#L3)
* Payment react native iOS: [link](https://github.com/stripe/stripe-react-native/blob/89907c7837caabf99d608ed3ec2182bbd9ecfe0b/stripe-react-native.podspec#L5)
* Payment react native Android: [link](https://github.com/stripe/stripe-react-native/blob/89907c7837caabf99d608ed3ec2182bbd9ecfe0b/android/gradle.properties#L3)

**To Reproduce**
* Build a app with both payment and identity plugin integrated
* The app should fail to build due to native SDK version conflicts

**Expected behavior**
The app should build correctly

Using Function:
- [x] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [x] Identity Verification Sheet

**Comment by ccen-stripe** [comment]
@rdlabo FYI :)

**Comment by rdlabo** [comment]
@ccen-stripe  Thanks for the Issue. This is for deprecated methods as per [sheet-definitions.interface.ts#L12-L14](https://github.com/capacitor-community/stripe/blob/main/packages/payment/src/identityverificationsheet/identity-verification-sheet-definitions.interface.ts#L12-L14) . We will deprecate it when Capacitor 6 is released or after about 6 months.
