### ISSUE TITLE
Connected Accounts

### ISSUE THREAD

**Issue by bmaguire5300** [capacitor-community/stripe#309]
**Platform**

- [x] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
Initializing Stripe with a connected account ID does not link payment intent confirms to this connected account. I am passing the customer ID of the connected account as well as the ephemeral key which has been generated for the customer of a connected account. I can see both ephemeral keys & payment intent events in the connected customer logs but confirming the payment with test info gives an "Unrecognized request URL" error.

**Expected behavior**
Stripe should initialize with the connected account ID

**Additional context**
```js 
async paymentSheet() {
    var keys: Keys;
    // Connect to your backend endpoint, and get every key.
    this.http
      .get<Keys>('api/AppBasket/GetStripeKeys')
      .subscribe({
        next: async (v) => {
          keys = v;
          // prepare PaymentSheet with CreatePaymentSheetOption.
          await Stripe.createPaymentSheet({
            paymentIntentClientSecret: keys.PaymentIntentClientSecret,
            customerId: keys.CustomerId,
            customerEphemeralKeySecret: keys.StripeEphemeralKey,
          });
          const result = await Stripe.presentPaymentSheet();
          if (result.paymentResult === PaymentSheetEventsEnum.Completed) {
            console.log('completed');
          }
        },
      });
  }
```
```js 
export class AppComponent {
  constructor() {
    Stripe.initialize({
      publishableKey: env.testKey,
      stripeAccount: env.ConnectedAccount,
    });
  }
}
```

Product Name: 
Product URL :
Using Function:
- [x ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
https://github.com/capacitor-community/stripe/blob/main/packages/payment/src/web.ts#L84

We set a value in stripeAccount. This appears to be a stripe-pwa-elements issue.

https://github.com/wpkyoto/stripe-pwa-elements

to raise an Issue.
