### ISSUE TITLE
Android build failed 

### ISSUE THREAD

**Issue by ipehimanshu** [capacitor-community/stripe#311]
Hello 

we today used latest version 5.3.0 and face build issue like

Dependency 'androidx.emoji2:emoji2-views-helper:1.4.0' requires libraries and applications that       depend on it to compile against version 34 or later of the       Android APIs. 

all good into 5.2.0

FYI

Capacitor CLI      : 5.5.0
   @capacitor/android : 5.2.3
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0
   
   Thank you

**Comment by rdlabo** [comment]
@ipehimanshu  Please submit your Issue according to the format. I don't know what package you are using so I can't comment.

**Comment by ipehimanshu** [comment]
@rdlabo 
ok we are using @capacitor-community/stripe@5.3.0

**Comment by ipehimanshu** [comment]
@rdlabo 

ok here is npx cap ls android info

[info] Found 11 Capacitor plugins for android:
       **@capacitor-community/stripe@5.3.0**
       @capacitor/app@5.0.6
       @capacitor/camera@5.0.7
       @capacitor/clipboard@5.0.6
       @capacitor/device@5.0.6
       @capacitor/haptics@5.0.6
       @capacitor/keyboard@5.0.6
       @capacitor/network@5.0.6
       @capacitor/share@5.0.6
       @capacitor/splash-screen@5.0.6
       @capacitor/status-bar@5.0.6
[info] Found 11 Cordova plugins for android:
       com.phonegap.plugins.nativesettingsopener@1.2.0
       cordova-plugin-calendar@5.1.6
       cordova-plugin-facebook-connect@3.2.0
       cordova-plugin-googleplus@8.5.2
       cordova-plugin-inappbrowser@5.0.0
       cordova-plugin-keychain-touch-id@3.3.0
       cordova-plugin-printer@0.8.0
       cordova-plugin-theme-detection@1.3.0
       cordova.plugins.diagnostic@7.1.3
       es6-promise-plugin@4.2.2
       pushwoosh-cordova-plugin@8.3.16
[info] Found 1 incompatible Cordova plugin for android, skipped install:
       cordova-plugin-sign-in-with-apple@0.1.2
       
      and here is build result from android studio
      
   2 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.emoji2:emoji2-views-helper:1.4.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 8.0.0 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdk of at least 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.emoji2:emoji2:1.4.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 8.0.0 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdk of at least 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).


NOTE
**If i downgrade stripe version to 5.2.0 then build success without error**

**Comment by rdlabo** [comment]
Thank you. This is due to the Stripe library version. Please fix as follows.

update minSdkVersion to 26 And compileSdkVersion to 34 in your `android/app/build.gradle` file:

```diff
  ext {
-    minSdkVersion = 22
-    compileSdkVersion = 33
+    minSdkVersion = 26
+    compileSdkVersion = 34
```

**Comment by AndreasKuhlmann** [comment]
The documentation should be updated accordingly (https://stripe.capacitorjs.jp/docs/configuration).

**Comment by rdlabo** [comment]
updated: https://github.com/ionic-jp/capacitor-plugins-docs/commit/e82bd5de79d318e78877bcfd0fffd929d093305c

Thanks for report!

**Comment by ipehimanshu** [comment]
Thank you
