### ISSUE TITLE
[iOS] Credit card number input field messed up

### ISSUE THREAD

**Issue by AndreasKuhlmann** [capacitor-community/stripe#312]
**Platform**

- [ ] Web
- [x] iOS
- [ ] Android

**Describe the bug**
Since v5.3.0 the credit card input field dosen't show icons any more and has become to small for entering credit card number

**To Reproduce**
1. Present paymentsheet

**Screenshots**
![IMG_4415](https://github.com/capacitor-community/stripe/assets/15803855/7b00511a-7961-4deb-a217-e9cece1f5766)

Product Name: 
Product URL :
Using Function:
- [x] Payment Sheet / Payment Flow
- [x] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
Thanks for the Issue. However, this plugin is a wrapper for Stripe's library.
Please discuss this issue at https://github.com/stripe/stripe-ios.
