### ISSUE TITLE
Adding PayPal

### ISSUE THREAD

**Issue by larsblumberg** [capacitor-community/stripe#317]
**Is your feature request related to a problem? Please describe.**

Some users want to pay via Stripe‘s PayPal method 

**Describe the solution you'd like**

PayPal is a working payment method offered by this plugin.

I’m happy to add this via PR. Is there something I should be aware of?

**Comment by larsblumberg** [comment]
PayPal actually works already. Closing.

**Comment by miraclemaker** [comment]
Have you managed to get PayPal to appear on iOS paymentsheet?

**Comment by larsblumberg** [comment]
No, unfortunately PayPal option doesn't appear on iOS yet. Related open issue: https://github.com/capacitor-community/stripe/issues/313

**Comment by larsblumberg** [comment]
At the end the Stripe Elements Web SDK works just fine.
