### ISSUE TITLE
Issue redirect on links within docs

### ISSUE THREAD

**Issue by bryce13950** [capacitor-community/stripe#32]
**Describe the bug**
When I land on this page https://capacitor-community.github.io/stripe/, and click on any link on the side I end up getting redirected to this wiki instead https://zyra.github.io/capacitor-stripe/installation. I am not sure if this is an issue with a cached GitHub redirect, or something, but I thought I would bring it to your attention in case there seems to be an obvious solution.

**Comment by ihadeed** [comment]
My apologies, I haven't updated the repo to update the docs via CI/CD like it used to.

For the time being you can find the docs here: https://github.com/capacitor-community/stripe/tree/master/.docs/pages

The docs will be updated soon to use the official Capacitor doc generator.

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
