### ISSUE TITLE
This doesn't work with ionic 7 on the web

### ISSUE THREAD

**Issue by stealth-d** [capacitor-community/stripe#320]
**Platform**

- [ ] Web

**Describe the bug**

> [Error] Failed to load resource: the server responded with a status of 504 (Outdated Optimize Dep) (stripe-payment-request-button.entry.js, line 0)

**To Reproduce**
1. `ionic start`
2. followed the docs for this plugin
3. `ionic serv`

**Expected behavior**
Not error and the app doesn't get stuck at 'loading...'

**Screenshots**
<img width="737" alt="Screenshot 2023-11-14 at 3 05 43 PM" src="https://github.com/capacitor-community/stripe/assets/147092891/8fcbdafb-38bd-41b3-a75f-e8eb4918fb83">

Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay

**Comment by stealth-d** [comment]
For those who wonder if they need this, nah, you can use [Stripe's official elements](https://stripe.com/docs/payments/payment-element), they'll work just fine in your native apps too..

**Comment by rdlabo** [comment]
This is same issue of https://github.com/capacitor-community/stripe/issues/320
Close this Issue as the Issue over there is more detailed.
