### ISSUE TITLE
Apple Pay not working on iPad

### ISSUE THREAD

**Issue by luis951** [capacitor-community/stripe#321]
**Platform**

- [ ] Web
- [X] iOS
- [ ] Android

**Describe the bug**
Apple Pay screen not being called on iPad, although working fine on iPhone.

**To Reproduce**
Call methods `createApplePay` and `presentApplePay`

**Expected behavior**
Apple Pay screen should open.

Using Function:
- [ ] Payment Sheet / Payment Flow
- [X] Apple Pay
- [ ] Google Pay
- [ ] Identity Verification Sheet

**Comment by rdlabo** [comment]
This is probably due to the iPad not being properly set up for payment.

**Comment by connectMyClub** [comment]
@luis951 We're experiencing the say. Apple Pay not working on iOS. Apple Pay is set up correctly on the device though. I'm wondering if the app needs to be downloaded from the App Store rather than installed from your Mac?

**Comment by rdlabo** [comment]
It looks like a clone of https://github.com/capacitor-community/stripe/issues/321, so go here.
