### ISSUE TITLE
We are getting error OR_BIBED_06 for Gpay even google_pay_is_testing set as true

### ISSUE THREAD

**Issue by ipehimanshu** [capacitor-community/stripe#322]
Hello 

We are using this plugin version  @capacitor-community/stripe@5.4.2

and here is npx cap ls

- copy android [info] Found 11 Cordova plugins for android:
       com.phonegap.plugins.nativesettingsopener@1.2.0
       cordova-plugin-calendar@5.1.6
       cordova-plugin-facebook-connect@3.2.0
       cordova-plugin-googleplus@8.5.2
       cordova-plugin-inappbrowser@5.0.0
       cordova-plugin-keychain-touch-id@3.3.0
       cordova-plugin-printer@0.8.0
       cordova-plugin-theme-detection@1.3.0
       cordova.plugins.diagnostic@7.1.4
       es6-promise-plugin@4.2.2
       pushwoosh-cordova-plugin@8.3.16
√ copy android in 5.33s
√ Updating Android plugins in 42.50ms
[info] Found 11 Capacitor plugins for android:
       @capacitor-community/stripe@5.4.2
       @capacitor/app@5.0.6
       @capacitor/camera@5.0.7
       @capacitor/clipboard@5.0.6
       @capacitor/device@5.0.6
       @capacitor/haptics@5.0.6
       @capacitor/keyboard@5.0.6
       @capacitor/network@5.0.6
       @capacitor/share@5.0.6
       @capacitor/splash-screen@5.0.6
       @capacitor/status-bar@5.0.6
| update android [info] Found 11 Cordova plugins for android:
       com.phonegap.plugins.nativesettingsopener@1.2.0
       cordova-plugin-calendar@5.1.6
       cordova-plugin-facebook-connect@3.2.0
       cordova-plugin-googleplus@8.5.2
       cordova-plugin-inappbrowser@5.0.0
       cordova-plugin-keychain-touch-id@3.3.0
       cordova-plugin-printer@0.8.0
       cordova-plugin-theme-detection@1.3.0
       cordova.plugins.diagnostic@7.1.4
       es6-promise-plugin@4.2.2
       pushwoosh-cordova-plugin@8.3.16
       
     we are trying to do google pay integration
     
    and we set enable_google_pay as true and google_pay_is_testing as true into strings.xml for android

also we are creating payment Intent using test mode details.

when doing payment we are getting error like

Request failed

This merchant is having trouble accepting

your payment at the moment. Try using a
different payment method. [OR_BIBED_06]

https://prnt.sc/-v8our5xoXdk

https://prnt.sc/xt2qFKc7PAVe

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1
   
  So let us know if anything we are doing wrong sir, 
  we first need to do test payment and then submit for production access.
  
  
  Thank you

**Comment by ipehimanshu** [comment]
Hello

we are using concept like

Main account key and pass stripe connected account ID
like below

stripe2.initialize({
      publishableKey:this.constant.STRIPE_PUBLISHABLE_KEY,
      stripeAccount:this.constant.stripeAccount
    });
    
  and more checking into android studio it says like
  
  
![carlax-android0debug-error](https://github.com/capacitor-community/stripe/assets/26652038/de917e1f-d33d-4efe-81d9-342c05ed62c2)

So as i am thinking it not taking stripeAccount 

can you please check and help us to fix it.

Thank you

**Comment by connectMyClub** [comment]
@ipehimanshu We saw this using GPay on testing. Works fine when your app is live. I think it is because your personal GPay account isn't a test account.

**Comment by rdlabo** [comment]
As @connectMyClub  says, it appears to be a configuration issue. Close this Issue.
