### ISSUE TITLE
countryCode only US

### ISSUE THREAD

**Issue by connectMyClub** [capacitor-community/stripe#327]
**Platform**

iOS

**Describe the bug**
Country always shows as United States on iOS despite setting countryCode to GB

**To Reproduce**
 ```
const createResult =    await Stripe.createPaymentSheet({
              paymentIntentClientSecret: clientSecret,
              customerId: customer,
              customerEphemeralKeySecret: ephemeralKey,
              merchantDisplayName: myMerchantName,
              countryCode: "GB",
              withZipCode: true,
              returnURL: "",
              enableApplePay: true,
              applePayMerchantId: merchantID,
              enableGooglePay: false,
              GooglePayIsTesting: false 
            });
```

**Expected behavior**
Country or region to show as UK

**Screenshots**

**Additional context**

**Usage Product**

Product Name: 
Product URL :
Using Function:
Payment Sheet

**Comment by rdlabo** [comment]
This is server side issue. Please check this:
https://github.com/capacitor-community/stripe/blob/main/demo/server/src/app.controller.ts#L35-L39
