### ISSUE TITLE
Google pay not available even in the react demo project

### ISSUE THREAD

**Issue by sxlwar** [capacitor-community/stripe#329]
**Platform**

- [ ] Web
- [ ] iOS
- [x] Android

**Describe the bug**
isGooglePayAvailable always false even the G-pay works properly on my device

**To Reproduce**
Build the demo/react project and install it on Android device

**Expected behavior**
Google Pay works fine

**Screenshots**

**Additional context**

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: 
Product URL :
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [x] Google Pay
- [ ] Identity Verification Sheet

**Comment by canercanbaz** [comment]
Same here, it says it does not support always.

![image](https://github.com/capacitor-community/stripe/assets/34982311/2c925a86-472b-4256-82fd-8da42952f695)

**Comment by canercanbaz** [comment]
Hello @rdlabo, sorry for mentioning you but I really need this. Do you have any idea why it does not work? Any comments or ideas?

**Comment by rdlabo** [comment]
OK. From my research, it appears that Google Pay may take some time to become available. In the demo, Google Pay was available after the isGooglePayAvailable run.
I will soon change isGooglePayAvailable to an EventListener. Please wait a little.

**Comment by canercanbaz** [comment]
Thanks a lot @rdlabo, I am looking forward to it!

**Comment by canercanbaz** [comment]
That seems to be working fine @rdlabo! Thanks a lot!

![image](https://github.com/capacitor-community/stripe/assets/34982311/0909a330-407f-4984-956e-b9ddf906a9a0)

**Comment by rdlabo** [comment]
Great!!

merge https://github.com/capacitor-community/stripe/pull/345 and released v5.5.1
Thanks.
