### ISSUE TITLE
Update iOS Stripe Pod dependency to 21.0.1

### ISSUE THREAD

**Issue by ihadeed** [capacitor-community/stripe#33]
OK, so even further investigation! it seems like there is an incompatibility with the newest version of the stripe library (21.0.1) It seems like there simply needs to be some updates done to the library to make it compatible i.e. change enums like `typeCard` to `card` etc. For whatever reason, the capacitor update is not respecting the major version number declared in the pod file, which is thus causing it to write out a pod lock file that has the incompatible version within it. 

_Originally posted by @bryce13950 in https://github.com/capacitor-community/stripe/issues/31#issuecomment-733974877_

**Comment by bryce13950** [comment]
All set! #34
