### ISSUE TITLE
Support paymentSummaryItems in PaymentFlow

### ISSUE THREAD

**Issue by thomasjohansen** [capacitor-community/stripe#339]
**Is your feature request related to a problem? Please describe.**
Support of paymentSummaryItems in PaymentFlow.

**Describe the solution you'd like**
As some countries requires setting this for setupIntent, extending the flow to support paymentSummaryItems would make the onboarding flow for customers easier.

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: Two products that still are in beta.
Product URL :
Using Function:
- [X] Payment Sheet / Payment Flow
- [X] Apple Pay
- [X] Google Pay
- [ ] Identity Verification Sheet

**Comment by thomasjohansen** [comment]
Here's Stripe's example:
https://docs.stripe.com/apple-pay?platform=ios#create-payment-request

The paymentSummaryItems seems already implemented on createApplePay https://github.com/capacitor-community/stripe/tree/main/packages/payment#createapplepay via the option prop paymentSummaryItems (https://github.com/capacitor-community/stripe/tree/main/packages/payment#createapplepayoption)

Wouldn't it be possible to use the same functionality?

**Comment by rdlabo** [comment]
This is a method for Apple Pay and cannot be used with PaymentFlow.

https://developer.apple.com/documentation/passkit_apple_pay_and_wallet
