### ISSUE TITLE
TestFlight IOs

### ISSUE THREAD

**Issue by egasystems** [capacitor-community/stripe#343]
**Platform**

- [X ] iOS

**Describe the bug**
It works for me compiling directly on my iPhone, when I go to production and download through testFlight it does not send me the sheet I see that this Stripe.addListener(ApplePayEventsEnum.Loaded) is activated. Could you tell me if there is any additional configuration to upload this to prod with Apple pay

**Screenshots**
![WhatsApp Image 2024-03-16 at 9 14 07 PM](https://github.com/capacitor-community/stripe/assets/84365216/87855585-8732-4e61-8695-18f6bf1c97ed)
![image](https://github.com/capacitor-community/stripe/assets/84365216/0d4ed665-6d9a-491a-b0ad-194587c7e068)

Using Function:

- [ X] Apple Pay

**Comment by fetrarij** [comment]
I confirm this  behaviour, the apple payment sheet opens on simulator or on a device directly compiled from xcode, but does not on testflight.

the result of presentApplePay() is directly {paymentResult: ApplePayEventsEnum.Canceled} without user's interaction

**Comment by fetrarij** [comment]
@egasystems in my code signing entitlements, there are already  both entitlements (debug & release)

**Comment by fetrarij** [comment]
I have it working, thanks

**Comment by rdlabo** [comment]
@egasystems Thanks good advice!! You resolved this issue!
