### ISSUE TITLE
RequestedConnectionToken trigger twice

### ISSUE THREAD

**Issue by divyesh-savaliya** [capacitor-community/stripe#347]
**Platform**

- [ ] Web
- [X] iOS
- [X] Android

**Describe the bug**
RequestedConnectionToken triggers twice on initializing, it also triggers when the app comes to the foreground from the background.
As well as when payment popup success, it also trigger RequestedConnectionToken.

Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [X] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment]
This is no plugin issue. This is requested by the Stripe SDK at any given time. If you think this is a serious problem, please raise the following Issue.

https://github.com/stripe/stripe-terminal-ios
https://github.com/stripe/stripe-terminal-android

**Comment by rdlabo** [comment]
@divyesh-savaliya Has this solved the problem? If so, close the Issue.
