### ISSUE TITLE
The client_secret provided does not match the client_secret associated with the PaymentIntent.

### ISSUE THREAD

**Issue by divyesh-savaliya** [capacitor-community/stripe#348]
**Platform**

- [ ] Web
- [X] iOS
- [X] Android

**Describe the bug**
If a previous request failed due to an error, attempting to make a payment again result in the following message: "The client_secret provided does not match the client_secret associated with the PaymentIntent."

**To Reproduce**

1. Make a payment using a real card while keeping the Stripe key in test mode.
2. This should result in a failed payment due to the mismatch between the live card and the test environment.
3. After the failed payment, attempt to call collectPaymentMethod with a new payment intent ID.
4. You should encounter an error message indicating that the client secret provided does not match the client secret associated with the PaymentIntent.
--------
Another way to reproduce
1. Connect to tap to pay
2. Put app in background and then open the app
3. Now try to make the payment
4. It throws the error

**Expected behavior**
It should open new payment sheet with new payment intent id.

**Additional context**
Clear previous payment intent info if its failed.

Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [X] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment]
> After the failed payment, attempt to call collectPaymentMethod with a new payment intent ID.

If failed, another card can be tried in succession. If change collectPaymentMethod  with PaymentIntent, you should run `cancelCollectPaymentMethod` before collectPaymentMethod.

**Comment by rdlabo** [comment]
> Another way to reproduce

There does not appear to be a problem at this time. For longer periods of time, the Secret Key is likely to change and a revert algorithm will be required.

https://github.com/capacitor-community/stripe/assets/9690024/361e2ee1-c0c6-47d3-a029-5ced917d6c2d

**Comment by rdlabo** [comment]
@divyesh-savaliya Has this solved the problem? If so, close the Issue.

**Comment by rdlabo** [comment]
Closed due to lack of comments for a long time.
