### ISSUE TITLE
Optional billing address with Apple Pay

### ISSUE THREAD

**Issue by josepedromonteiro** [capacitor-community/stripe#35]
If it is possible the billing address should be optional with Apple Pay payments

**Current behavior**
When paying with apple pay a billing address must be sent

**Desired behavior**
While paying with apple pay the billing address should not be mandatory

**Comment by JoshuvaGeorge03** [comment]
@josepedromonteiro Is apple pay working for you? I can't able to make it work.  could you please take a look at the below screenshot and let me know what might be wrong?
![2021-01-18](https://user-images.githubusercontent.com/39693066/104995637-9f350b00-5a4c-11eb-9781-def3285c6559.jpg)

I am doing everything the same as told in the documentation.




`
 capacitor-community/stripe: 1.1.0

Ionic:

   Ionic CLI                     : 6.12.3 (/home/joshuva/.nvm/versions/node/v12.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.0.7
   @angular/cli                  : 11.0.7
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.20.0 (/home/joshuva/.nvm/versions/node/v12.20.0/bin/node)
   npm    : 6.14.10
   OS     : Linux 5.8

`

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
