### ISSUE TITLE
Google Pay not working for createPaymentFlow

### ISSUE THREAD

**Issue by thomasjohansen** [capacitor-community/stripe#354]
In the demo app, Google Pay is working fine with the Google Pay flow.

But I cannot get PaymentFlow to work with Google Pay (enableGooglePay: true) in confirmPaymentFlow().

I can create and present the flow, and selecting Google Pay seems to work, but when doing the Confirm I'm getting:
Request failed.
This merchan is having trouble accepting our payment right now. Try using a different payment method. [OR_BIBED_11].

Is this not supported?

**Comment by rdlabo** [comment]
Please check this url: https://stackoverflow.com/questions/76655117/or-bibed-11-error-in-google-pay-api-for-production-environment

This error is not this plugin issue. Thanks.
