### ISSUE TITLE
PaymentFlowEventsEnum.FailedToLoad always triggered

### ISSUE THREAD

**Issue by lsantaniello** [capacitor-community/stripe#357]
**Platform**

- [x] Web
- [x] iOS

**Describe the bug**
I Implemented **Payment Flow without customer** in my ionic capacitor angular app but When I create Payment Flow, the FailedToLoad event always triggered.

**PaymentFlowEventsEnum.FailedToLoad** always triggered.
```
   Stripe.addListener(PaymentFlowEventsEnum.FailedToLoad, () => {
      console.log('PaymentFlowEventsEnum.FailedToLoad');
    });
```
In the demo there is a method **createPaymentFlow(withCustomer = true)** but it is called always with withCustomer=true.

I seen that demo receives **three parameters**: 
- "paymentIntent"
- "ephemeralKey":
- "customer"

In my app I create payment Intent server side with **one parameter**:
- paymentIntent

My server id developed in **PHP**

_My question is: Is it ok or all parameters are required?_

Using Function:
- [x] Payment Sheet / Payment Flow

**Comment by rdlabo** [comment]
I checked and it seems to be working fine in the demo. I think the problem may be elsewhere.

The API for the demo is as follows
https://github.com/capacitor-community/stripe/blob/main/demo/server/src/app.controller.ts#L76-L92

Please ask the Stripe team about the API, as it is not related to the plugin.

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. If you still have issues, please open a new Issue. Best regards.
