### ISSUE TITLE
Support capacitor 6.1.0

### ISSUE THREAD

**Issue by malua** [capacitor-community/stripe#362]
**Describe the bug**
The package cannot be installed with capacitor core version > 6.0.0. Also the the package on npm is behind. Version 6 is only available in the next tag.

**To Reproduce**
Install the package with @capacitor/core@6.1.0

Thank you for your support!

**Comment by derekps** [comment]
+1

**Comment by rdlabo** [comment]
Thanks for the Issue. This was a complete failure on my part.
Fixed and released v6.0.2. Please try this. Thanks.

**Comment by malua** [comment]
No worries, thanks for the quick fix :)
