### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module: stripe-payment-sheet.entry.js after build

### ISSUE THREAD

**Issue by Bekzod101001** [capacitor-community/stripe#363]
Stack: Vue + Capacitor
- [x] Web

After build, when i'm calling Stripe.presentPaymentSheet() im having error:
index-CCJaHZvd.js:36 TypeError: Failed to fetch dynamically imported module: /assets/stripe-payment-sheet.entry.js.
This file even doesn't exist in built dist folder

- call Stripe.presentPaymentSheet() function

It works fine, when running it with npm run dev, but after build - everything crashes

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/a458f71b-4bf5-4343-94dd-c89242a3e33f">

**Additional context**
package.json:
  "dependencies": {
    "@capacitor-community/stripe": "^6.0.2",
    "@capacitor/android": "^6.0.0",
    "@capacitor/cli": "^6.0.0",
    "@capacitor/core": "^6.0.0",
    "@capacitor/haptics": "^6.0.0",
    "@capacitor/ios": "^6.0.0",
    "@types/html-truncate": "^1.2.4",
    "@vuelidate/core": "^2.0.3",
    "@vuelidate/validators": "^2.0.4",
    "axios": "^1.7.2",
    "hammerjs": "^2.0.8",
    "html-truncate": "^1.2.2",
    "normalize.css": "^8.0.1",
    "pinia": "^2.1.7",
    "stripe-pwa-elements": "^2.1.0",
    "swiper": "^11.1.4",
    "vue": "^3.4.21",
    "vue-axios": "^3.5.2",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@capacitor/assets": "^3.0.5",
    "@rushstack/eslint-patch": "^1.8.0",
    "@tsconfig/node20": "^20.1.4",
    "@types/hammerjs": "^2.0.45",
    "@types/jsdom": "^21.1.6",
    "@types/node": "^20.12.5",
    "@types/swiper": "^6.0.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue/eslint-config-prettier": "^9.0.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "@vue/test-utils": "^2.4.5",
    "@vue/tsconfig": "^0.5.1",
    "cypress": "^13.7.2",
    "eslint": "^8.57.0",
    "eslint-plugin-cypress": "^2.15.1",
    "eslint-plugin-vue": "^9.23.0",
    "jsdom": "^24.0.0",
    "npm-run-all2": "^6.1.2",
    "prettier": "^3.2.5",
    "sass": "^1.77.3",
    "start-server-and-test": "^2.0.3",
    "typescript": "~5.4.0",
    "unplugin-auto-import": "^0.17.6",
    "vite": "^5.2.8",
    "vite-plugin-vue-devtools": "^7.0.25",
    "vitest": "^1.4.0",
    "vue-tsc": "^2.0.11"
  }

Using Function:
- [x] Payment Sheet / Payment Flow

**Comment by rdlabo** [comment]
This issue is clone of https://github.com/capacitor-community/stripe/issues/328
Please discuss in this Issue.
