### ISSUE TITLE
Listener called multiple times

### ISSUE THREAD

**Issue by lsantaniello** [capacitor-community/stripe#364]
**Platform**

- [ ] Web
- [x ] iOS
- [ x] Android

**Describe the bug**
I integrated Stripe Capacitor library in my Ionic Angular App. I registered listeners in order to call my server when payment completed. 

I register listeners when the user enters the checkout page.

If the user goes to the checkout page but then thinks better of it and goes back to another page in the app, I would like to destroy the listeners.

If the user returns to the checkout page, I create new listeners.

When the user finalizes the payment, there are N listeners listening.

how can I solve it? I would like to use the ngOnDestroy method but how do I destroy the listeners?

**Comment by rdlabo** [comment]
The listener can remove by using `remove()`. ex: https://github.com/capacitor-community/stripe/blob/main/demo/angular/src/app/sheet/sheet.page.ts#L165

This is not plugin issue. please check capacitor docs.
