### ISSUE TITLE
Multiple Payment problem

### ISSUE THREAD

**Issue by lsantaniello** [capacitor-community/stripe#365]
**Platform**

- [ ] Web
- [ ] iOS
- [ x] Android

**Describe the bug**
1. I complete Payment Flow Successfully
2. Then I create another payment flow, open modal where I can insert credit card number
3. I want cancel and click on X icon to close modal
4. Created Event triggered and then Completed event. Why?

**Comment by rdlabo** [comment]
Have you REMOVED the before event listener?
