### ISSUE TITLE
"Expired API Key provided" error when attempting to collect payment method

### ISSUE THREAD

**Issue by wadeleveille** [capacitor-community/stripe#367]
**Platform**

- [ ] Web
- [ ] iOS
- [X] Android

**Describe the bug**
We are using the stripe terminal plugin to accept tap/chip payments with a USB connected M2 reader.  After a few hours, we receive the following error, and the device is not able to recover, and needs to be rebooted:  
```Capacitor: Sending plugin error: {"save":false,"callbackId":"130102328","pluginId":"StripeTerminal","methodName":"collectPaymentMethod","success":false,"error":{"message":"Expired API Key provided: pss_live_YW*********************************************************************_******WZYA"}}```

Questions:
1. At what point does the API key get refreshed?  When it expires, is that handled by the RequestedConnectionToken notification?
2. What is the difference between the terminal connection token (pst_live_...) and the api key (pss_live_...)?
3. Is there a proper sequence of events we can implement to avoid this error?

Our flow is the following:
***On device start***
1. Subscribe to all of the events, (eg:  RequestedConnectionToken, ConnectedReader, etc)
2. Call terminal.initialize()
3. Call terminal.discoverReaders()
4. Call terminal.connectReader()

***On payment required***
1. await terminal.collectPaymentMethod()
2. await terminal.confirmPaymentIntent()

**To Reproduce**
See above

**Expected behavior**
The api key should be refreshed automatically when needed, before throwing an error in terminal.collectPaymentMethod()

**Screenshots**
N/A

**Additional context**
We have also tried disconnecting/reconnecting every time a payment is required, but occasionally the terminal.disconnectReader() will fail.  Should we have to disconnect after every successful payment?

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: Stripe M2 Reader
Product URL:  https://stripe.com/terminal/m2
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [X] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment]
> At what point does the API key get refreshed? When it expires, is that handled by the RequestedConnectionToken notification?

Yes. You must obtain a new Token each time.

> What is the difference between the terminal connection token (pst_live_...) and the api key (pss_live_...)?

Sorry, I don't grasp the difference - ask the Stripe team.

> Is there a proper sequence of events we can implement to avoid this error?

Handled by Stripe's RequestedConnectionToken.
