### ISSUE TITLE
Incorrect Definition For AddListener(TerminalEventsEnum.DiscoveredReaders)

### ISSUE THREAD

**Issue by miccav-eventlink** [capacitor-community/stripe#369]
**Platform**

- [ x] Web
- [ x] iOS
- [x ] Android

**Describe the bug**
The file definitions.d.ts requires proper arguments to be defined for the method "addListener(eventName: TerminalEventsEnum.DiscoveredReaders,...)"

**Expected behavior**
`addListener(eventName: TerminalEventsEnum.DiscoveredReaders, listenerFunc: (readers: 
    ReaderInterface[]) => {
        reader: ReaderInterface;
    }): Promise<PluginListenerHandle>;`

**Additional context**

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: 
Product URL :
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [x ] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment]
Thanks for issue. This is fixed https://github.com/capacitor-community/stripe/pull/359/files
Please wait a little longer as it will be included in the next release.

**Comment by rdlabo** [comment]
https://github.com/capacitor-community/stripe/releases/tag/v6.1.0 resolve this issue. Thanks for issue!
