### ISSUE TITLE
Plugin locale

### ISSUE THREAD

**Issue by cihakmar** [capacitor-community/stripe#370]
Is it possible to make  Payment Sheet  multilingual? For now I cannot change  Payment Sheet  or  Payment Flow language if user switch app`s language.

Thanks

**Comment by rdlabo** [comment]
The Language of the Payment Sheet follows the settings of the application. This is not a plugin issue and will be closed.

**Comment by cihakmar** [comment]
@rdlabo OK, so can you please guide me what should I search? On android the sheet is in a correct language but on iOS is still in English....

**Comment by rdlabo** [comment]
Maybe, only localization settings issue. Please check this:

<img width="900" alt="スクリーンショット 2024-08-14 午後6 51 10" src="https://github.com/user-attachments/assets/1b238526-34f2-4211-b3be-724e77fde34d">

**Comment by cihakmar** [comment]
@Perfect, that's it. Is there a possibility to change this localization when user change his language in the app?

**Comment by rdlabo** [comment]
User can change device language settings.
