### ISSUE TITLE
Pod error

### ISSUE THREAD

**Issue by ralonsokichink** [capacitor-community/stripe#379]
After I try to update to capacitor v6 and run npx cap sync I got this error:

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "StripePaymentSheet":
        In snapshot (Podfile.lock):
        StripePaymentSheet (= 23.17.2, ~> 23.17.1)
        
        In Podfile:
        CapacitorCommunityStripe (from `../../node_modules/@capacitor-community/stripe`) was resolved to 6.2.1, which
        depends on
        StripePaymentSheet (~> 23.29.0)
        
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * changed the constraints of dependency `StripePaymentSheet` inside your development pod
        `CapacitorCommunityStripe`.
        You should run `pod update StripePaymentSheet` to apply changes you've made.

**Comment by rdlabo** [comment]
You should run command `pod install --repo-update` (or `pod update`) at `ios/App`.

**Comment by ralonsokichink** [comment]
I already did but still getting same message.

% pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "StripePaymentSheet":
  In snapshot (Podfile.lock):
    StripePaymentSheet (= 23.17.2, ~> 23.17.1)

  In Podfile:
    CapacitorCommunityStripe (from `../../node_modules/@capacitor-community/stripe`) was resolved to 6.2.1, which depends on
      StripePaymentSheet (~> 23.29.0)


You have either:
 * changed the constraints of dependency `StripePaymentSheet` inside your development pod `CapacitorCommunityStripe`.
   You should run `pod update StripePaymentSheet` to apply changes you've made.

**Comment by rdlabo** [comment]
Please try to remove `Podfile.lock`.

**Comment by rdlabo** [comment]
This is not a plugin issue and will be closed.
