### ISSUE TITLE
Discover multiple readers with different methods

### ISSUE THREAD

**Issue by kyleabens** [capacitor-community/stripe#380]
Not sure if it's possible in it's current state (doesn't look like it is) but can we please discovery multiple readers at once so we can list all options. I'm currently trying to do the following but doesn't seem to work.

```
const tapToPay = await StripeTerminal.discoverReaders({
        type: TerminalConnectTypes.TapToPay,
        locationId: ***********
      });

      const bluetooth = await StripeTerminal.discoverReaders({
        type: TerminalConnectTypes.Bluetooth,
        locationId: ***********
      });

      const internet = await StripeTerminal.discoverReaders({
        type: TerminalConnectTypes.Internet,
        locationId: ***********
      });
```

**Comment by rdlabo** [comment]
DiscoverReaders cannot be done at the same time. This is a Stripe Terminal specification.

**Comment by rdlabo** [comment]
This Issue is closed due to a long period of inactivity. If you still have issues, please open a new Issue. Best regards.
