### ISSUE TITLE
Duplicate class on Android build

### ISSUE THREAD

**Issue by karen1au** [capacitor-community/stripe#385]
**Platform**

- [ ] Web
- [ ] iOS
- [x] Android

**Describe the bug**
When use with "@capacitor/live-updates" the build is failing with 
```
Duplicate class org.bouncycastle.x509.X509StreamParserSpi found in modules
        bcprov-jdk15on-1.65 (org.bouncycastle:bcprov-jdk15on:1.65) and bcprov-jdk15to18-1.69
        (org.bouncycastle:bcprov-jdk15to18:1.69)
```
Is there anyway to force/exclude this dependency resolution?
Thanks!

**Comment by rdlabo** [comment]
Thanks for review. This is not a plugin issue. I know there are ways to remove duplicate packages like this:
https://github.com/capacitor-community/stripe/blob/main/packages/identity/android/build.gradle#L70-L72

but it is difficult to support directly.

**Comment by rdlabo** [comment]
Perhaps this is the kind of response we can provide.

```
dependencies {
    implementation("com.stripe:stripe-android:$stripeAndroidVersion") {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
    }
}
```

But either way, this is not a plugin issue and will be closed.
