### ISSUE TITLE
Connection Token is not setted

### ISSUE THREAD

**Issue by SossenSystems** [capacitor-community/stripe#397]
**Platform**

- [ ] Web
- [ ] iOS
- [ X] Android

**Describe the bug**
On iOS everything works great with tap to pay, but on Android it's currently not working because of the connection token over a custom provider is not setted and it comes to an following stacked error:
```
Uncaught (in promise) CapacitorException: Timed out waiting for connection token
    at returnResult (<anonymous>:943:32)
    at cap.fromNative (<anonymous>:925:17)
    at <anonymous>:1:18

CapacitorException: Unknown error retrieving payment intent from API
    at returnResult (<anonymous>:943:32)
    at cap.fromNative (<anonymous>:925:17)
    at <anonymous>:1:18
```

and sometimes it tries to set the connection token, but with the following error:
```
native StripeTerminal.setConnectionToken (#64254552)
result StripeTerminal.setConnectionToken (#64254552)
Uncaught (in promise) CapacitorException: Stripe Terminal do not pending fetchConnectionToken
    at returnResult (<anonymous>:943:32)
    at cap.fromNative (<anonymous>:
```

**To Reproduce**
``` TypeScript
        await StripeTerminal.addListener(TerminalEventsEnum.RequestedConnectionToken, async () => {
            console.log('waiting for token')
            const response = await api.getStripeConnectionToken
            if (response.status !== 200) return
            await StripeTerminal.setConnectionToken({token: response.data.token});
        });
```
It's never emitted and yes i run it before the initializing progress.

After that i run:
```
                    await StripeTerminal.initialize({isTest: true})
                    await api.tapToPay.connect()
```

More code snippets:
```

                async start(paymentIntent: string) {
                    if (!apiStore.isTerminalConnected && !apiStore.isTerminalConnecting) {
                        await api.tapToPay.connect()
                    }
                    try {
                        // Collect payment intent
                        await StripeTerminal.collectPaymentMethod({paymentIntent: paymentIntent});

                        try {
                            // Process and confirm payment intent
                            await StripeTerminal.confirmPaymentIntent();
                        } catch (e) {
                            console.error("Error on confirm payment intent", e);
                            await api.tapToPay.disconnect()
                            return {status: 'canceled', errorMessage: e}
                        }
                        await api.tapToPay.disconnect()
                        return {status: 'succeeded', errorMessage: null}
                    } catch (e) {
                        await api.tapToPay.disconnect()
                        console.error(e)
                        return {status: 'aborted', errorMessage: e}
                    }
                },
                async connect() {
                    if(apiStore.isTerminalConnecting){
                        return
                    }
                    apiStore.setTerminalConnectedState(false)
                    if(apiStore.getStripeLocationId.length === 0)
                        await api.auth.getTapToPayDetails()

                    await StripeTerminal.disconnectReader()
                    const {readers} = await StripeTerminal.discoverReaders({
                        type: TerminalConnectTypes.TapToPay,
                        locationId: apiStore.getStripeLocationId,
                    });

                    apiStore.setTerminalConnectingState(true)
                    await StripeTerminal.connectReader({
                        reader: readers[0]
                    });
                    apiStore.setTerminalConnectingState(false)
                    apiStore.setTerminalConnectedState(true)
                },
                async disconnect() {
                    await StripeTerminal.disconnectReader();

                    apiStore.setTerminalConnectedState(false)
                    apiStore.setTerminalConnectingState(false)
                }

```

Product Name: 
Product URL :
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [ X] Terminal（@capacitor-community/stripe-terminal）

**Comment by dave-morgan** [comment]
I have seen this error when location permissions are not set on Android prior to Stripe initialisation. IOS doesn't require this which is why it appears to work on IOS.

**Comment by rdlabo** [comment]
Thanks for the Issue. I don't know the details of “over a custom provider”, but first tell me if this plugin is broken or if you want a feature that is not implemented.

And if you suspect the plugin itself is broken, please let me know if you can reproduce it on https://github.com/capacitor-community/stripe/tree/main/demo/angular.

Best regards.

**Comment by SossenSystems** [comment]
Sorry, I expressed myself a bit stupidly, there is no “over a custom provider“, I actually meant the “set string token“ method.

I use /packages/terminal and just want to make Tap to Pay work, which works on iOS with the code on Android it doesn't work and it looks like a broken plugin.

I have also configured everything as the documentation says for Android in Android Studio.

I will test the Angular project from you tomorrow, I have ordered a Samsung Galaxy A15 especially for Tap to Pay on Android, which will arrive tomorrow. Before that I had to borrow a Google Pixel.

Best regards.

**Comment by rdlabo** [comment]
I was convinced.

> Timed out waiting for connection token

In many cases, the timing to Listen for TerminalEventsEnum.RequestedConnectionToken is too late, and the request has run before that time. Or setConnectionToken is taking too long.

I recommend that you Listen to TerminalEventsEnum.RequestedConnectionToken as soon as possible.

**Comment by SossenSystems** [comment]
I have now been able to solve the problem. It was apparently due to the payment intent, as “link“ was included, strangely enough iOS didn't care, Android absolutely did, but okay Stripe also says that in the documentation and that wouldn't make any sense.

**Comment by rdlabo** [comment]
Glad to hear the problem has been resolved!
