### ISSUE TITLE
Provide a more detailed error object to the consumer

### ISSUE THREAD

**Issue by shiv19** [capacitor-community/stripe#398]
**Is your feature request related to a problem? Please describe.**
Currently most of the failure handlers are rejecting the call with the localizedErrorMessage from the exception.
Sometimes we might need to use a different message based on the Stripe ApiError code, or a Stripe Decline Code.

**Describe the solution you'd like**
Instead of call.reject, we should call.resolve with `error: true` and then additional info about the error such as error code, decline code, error message, etc.
This will provide a more rich error handling experience.

**Usage Product**
We're currently integrating this plugin into a Capacitor mobile app where field service technicians can take payments using Stripe terminal or Stripe tap to pay.

**Additional Context**
If there is interest to take the project in this direction, I'm happy to contribute to this.

Using Function:
- [x] Terminal（@capacitor-community/stripe-terminal）

**Comment by rdlabo** [comment]
Thanks for the idea. For example, what about passing an exception object to call.reject, I feel it's not a good design to handle errors with resolve.

```
call.reject(exception.getLocalizedMessage(), null, exception);
```

Would this solve your problem?

**Comment by shiv19** [comment]
@rdlabo Ah, I didn't realize call.reject is overloaded. I assumed it only takes a string "message".
Yeah that could work. Let me experiment with that and see what capacitor side receives when we reject like this.
![image](https://github.com/user-attachments/assets/96eeacae-ab70-484c-94f2-2bffb12d63ae)

**Comment by shiv19** [comment]
I'm mainly looking to get the decline code that is listed in this table when something fails
https://docs.stripe.com/declines/codes

The failure can happen either on Collect Payment Method, or on Confirm Payment Intent

If the failure occurs during Collect Payment Method,
then the decline code is the Stripe API error `code`

If the failure occurs during Confirm Payment Intent,
then the decline code is present in exception -> payment intent -> last payment error -> decline_code

The reason why I'm after this code is because my product team wants to use custom error message based on certain decline codes from that table above and present the user with up to 2 follow up actions.

For now I've just ended up extracting the correct code and sending it in the message field of call.reject,
`https://github.com/simPRO-Software/stripe/commits/simpro/`

I'd rather work towards something that can fit well with the capacitor-community implementation so that I don't have to maintain a fork.

**Comment by shiv19** [comment]
Here's what I tried

```
confirmPaymentIntentCall.reject(exception.getLocalizedMessage(), errorCode, exception);
```

With that, when I console.dir the error, I just get the message and the code, not the full exception object.
![image](https://github.com/user-attachments/assets/6a00fc3a-3ed6-4b3d-84e9-ce82e6315133)

Since all I'm interested in is the code, perhaps we can add this back to the `@capacitor-community/stripe-terminal` plugin?

**Comment by shiv19** [comment]
https://github.com/ionic-team/capacitor/blob/74c3e9447e1e32e73f818d252eb12f453d849e8d/core/src/util.ts#L30C21-L30C34
Maybe it needs to be a JSObject, let me try that again.

**Comment by shiv19** [comment]
@rdlabo Bingo, yeah that works, thanks for pointing me in the right direction.
![image](https://github.com/user-attachments/assets/6e69bcb2-4d38-44b4-b0ee-40a2ccf1ae68)

**Comment by rdlabo** [comment]
@shiv19  Good!! Good! Just a little too busy this week to do this work. Can I get a pull request if you can? I will try to get time for a review somewhere.

**Comment by shiv19** [comment]
@rdlabo I might also only get to work on this on Tuesday. It is a long weekend in NZ.
But please leave this to me. I'll assign this issue to me now.

**Comment by rdlabo** [comment]
@shiv19  A LONG weekend is a wonderful thing! Unfortunately I am spending my weekend working. LOL!

I eagerly await your pull requests!

**Comment by rdlabo** [comment]
close by https://github.com/capacitor-community/stripe/releases/tag/v6.2.2
Thanks!
