### ISSUE TITLE
"No such module 'Stripe3DS2'" for Version 1.1.0

### ISSUE THREAD

**Issue by DwieDima** [capacitor-community/stripe#40]
**Describe the bug**
since `@capacitor-community/stripe` `1.1.0` i cannot build the app because of an xcode error.

**To Reproduce**
1. ionic capacitor build ios
4. build the app in xcode

**Expected behavior**
app should compile

**Screenshots**

![image](https://user-images.githubusercontent.com/26873275/101368631-a8f11d80-38a7-11eb-8714-3da094a15580.png)

**Desktop:**
 - OS: Mac OS 10.15.7
 - Browser: Chrome

**Smartphone:**
 - Device: iPhone 11 Pro
 - OS: IOS 14.2

**Comment by DwieDima** [comment]
#update 

updating cocoapods to 1.10.0 fixed this issue

https://stackoverflow.com/questions/64948546/swift-no-such-module-stripe3ds2-after-updating-stripe-to-21-0-1/64948631

**Comment by salman-trimulabs** [comment]
its not working even after updating cocoapods to 1.10.0
