### ISSUE TITLE
Android app crash reported by user

### ISSUE THREAD

**Issue by manpreet-stripe** [capacitor-community/stripe#408]
**Platform**

- [ ] Web
- [ ] iOS
- [ x] Android

**Describe the bug**
https://github.com/capacitor-community/stripe/issues/368#issuecomment-2472959781

**Expected behavior**
Android app shouldn't crash using CapacitorJS 

Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [ ] Google Pay
- [x] Identity (@capacitor-community/stripe-identity)
- [ ] Terminal（@capacitor-community/stripe-terminal）

cc: @rdlabo

**Comment by rdlabo** [comment]
Thanks for issue. This is clone of https://github.com/capacitor-community/stripe/issues/368
I have reopened this Issue and will close this one.
