### ISSUE TITLE
isGooglePayAvailable return UNIMPLEMENTED after upgrade version to 6.4.2 

### ISSUE THREAD

**Issue by ChingHong19980819** [capacitor-community/stripe#416]
**Platform**

- [ ] Web
- [ ] iOS
- [x] Android

**Describe the bug**
After upgrading the plugin to the latest version, the isGooglePayAvailable method returns UNIMPLEMENTED, which was not an issue in the older version. Additionally, when calling createGooglePay, the app crashes and closes automatically. I have followed the latest Google Pay setup instructions in the documentation, but the issue persists. Furthermore, my phone has the Google Wallet app installed and a card already bound to it. The same issue is observed in the demo app provided with the plugin. The Ionic version used is Capacitor 6.

 The Ionic version used is Capacitor 6. Tried on 

**To Reproduce**
1. Update the plugin to the latest version.
2. Call the isGooglePayAvailable method.
3. Observe the UNIMPLEMENTED error.
4. Call createGooglePay.
5. Notice the app crashes and closes immediately.

**Expected behavior**
1. The isGooglePayAvailable method should correctly check and return whether Google Pay is available on the device.
2. The createGooglePay method should initialize the Google Pay process without causing the app to crash

**Screenshots**

**Additional context**
The issue occurs only after upgrading to the latest version of the plugin. Previous versions did not have these problems.

**Usage Product**
If you adopt this plugin, please let us know which product you are using.

Product Name: 
Product URL :
Using Function:
- [ ] Payment Sheet / Payment Flow
- [ ] Apple Pay
- [x] Google Pay
- [ ] Identity (@capacitor-community/stripe-identity)
- [ ] Terminal（@capacitor-community/stripe-terminal）

**Comment by alice39** [comment]
The PR #415 fixes it, the only affected versions are 6.4.2 (latest) and 6.4.1 when rewriting from Java to Kotlin happened

**Comment by ChingHong19980819** [comment]
Thank you, it is working now!

**Comment by rdlabo** [comment]
Sorry for the inconvenience. This bug has been fixed in v6.4.3 by merging a pull request by @alice39.
