### ISSUE TITLE
Getting payment method ID from stripe.paymentRequest()

### ISSUE THREAD

**Issue by LinnaeK** [capacitor-community/stripe#44]
We are trying to implement Apple Pay into our capacitor app. We use Stripe's [paymentRequest](https://stripe.com/docs/js/payment_request/create) method to retrieve a payment method ID from Stripe which we then pass onto our API for it to use in completing the charge with Stripe. We have been unable to find a solution that allows us to use Stripe's Apple Pay flow to get a payment method ID without creating a pop up browser. 

Will you be incorporating functions that will allow users to access payment method IDs with Stripe's most current functions? Do you have an idea of the timeline for completion?

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
