### ISSUE TITLE
redirectUrl in confirmPaymentIntent

### ISSUE THREAD

**Issue by stefanotauriello** [capacitor-community/stripe#47]
In a mobile app with Capacitor, is it required? Which is the right value in an app?

**Comment by ihadeed** [comment]
It's used on Android devices when performing browser based 3DS authentication.

Not sure, but IIRC it's supposed to be a URL that will open your app (i.e universal or deep link). The exact path doesn't matter since Stripe SDK will take over from there.

**Comment by HardikDG** [comment]
@ihadeed So to use Stripe SDK plugin we need to use any service, which will work as universal or deep link?

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
