### ISSUE TITLE
Use 2 Publishable key is not possible

### ISSUE THREAD

**Issue by stefanotauriello** [capacitor-community/stripe#48]
How can I use 2 different Publishable key (2 different account Stripe) in the same app?
I’m testing on iOS (but I think it will be so in Android).
They are in different sections but if I set publishablekey then it can't be replaced, but use always the first I set because give me an error on confirmPaymentIntent that it doesn’t find PaymentIntent but server side is ok.
Is there a solution?

in the cordova-plugin-stripe seems to be resolved 
https://github.com/zyra/cordova-plugin-stripe/issues/18

**Comment by stefanotauriello** [comment]
Anyone can Help me, please?

**Comment by amakhonin** [comment]
you can set different key for STPAddCardViewController or STPAPIClient. Stripe.setDefaultPublishableKey seems to not changing key

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
