### ISSUE TITLE
3DS Authentication after confirmPaymentIntent

### ISSUE THREAD

**Issue by stefanotauriello** [capacitor-community/stripe#50]
After confirmPaymentIntent I'm receiving in the response:

`"id": "pi_*****",
  "object": "payment_intent",
  "last_payment_error": null,
  "livemode": true,
  "next_action": {
    "type": "use_stripe_sdk",
    "use_stripe_sdk": {
      "type": "three_d_secure_redirect",
      "stripe_js": "https://hooks.stripe.com/redirect/authenticate/src_*******?client_secret=src_client_secret_*******",
      "source": "src_********"
    }
  },
  "status": "requires_action",`

In the Stripe's documentation ([https://stripe.com/docs/payments/3d-secure#check-status](url)) is explained with 'redirect_to_url' instead of 'use_stripe_sdk'.

Who can help me,please?

**Comment by stefanotauriello** [comment]
I've now received a succeeded payment after requires_action, so maybe it is already managed by this plugin and the problem was the client who don't authenticate it. I'm confused 😩

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
