### ISSUE TITLE
Missing Stripe POD

### ISSUE THREAD

**Issue by cambronjay** [capacitor-community/stripe#53]
**Describe the bug**
The Stripe Pod is missing from the list of pods to install.
**To Reproduce**
Install the plugin, build the app, and then do npx cap sync

**Expected behavior**
The plugin should include the Stripe Pod by putting its reference into the Podfile
**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version Latest

**Smartphone (please complete the following information):**
 - Device:  [iPhone X]
 - OS: Latest
 
**Additional context**
Here is the error
[error] Error running update: Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    CapacitorCommunityStripe (from `../../node_modules/@capacitor-community/stripe`) was resolved to 0.0.1, which depends on
      Stripe (= 21.0.1)

**Comment by cambronjay** [comment]
I was able to fix the issue by removing the dependency version on the podspec file and then placing  pod 'Stripe', '~> 21.0.1' in both targets in the podfile

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
