### ISSUE TITLE
iOS Stripe.payWithApplePay() returns 'unable to parse apple pay options'

### ISSUE THREAD

**Issue by giuseeFG** [capacitor-community/stripe#54]
I'm trying to call "**payWithApplePay**" in this way:

```
                    Stripe.payWithApplePay({
                        applePayOptions: {
                            merchantId: 'merchant.xxx.xxx',
                            country: 'IT',
                            currency: 'EUR',
                            items: [{
                                label: 'my_item_name',
                                amount: '1'
                            }]
                        }
                    }).then((res: any) => {
                        console.log('RES', res);
                    }).catch((e: any) => {
                        console.error('ERROR ', e);
                    });
```

I'm, ALWAYS getting this response in xCode:

```
{
  "errorMessage": "Impossibile completare l'operazione. (Errore CapacitorCommunityStripe.StripePluginError 0).",
  "message": "unable to parse apple pay options: Impossibile completare l'operazione. (Errore CapacitorCommunityStripe.StripePluginError 0)."
}
```

The configuration on Stripe has been made correctly:

![Schermata 2021-02-01 alle 15 05 31](https://user-images.githubusercontent.com/6843774/106469025-fdc3a580-649e-11eb-8602-58a777c4d01e.png)

**Google Pay**, instead, works like a charm!

Can anybody help me?

**Comment by moblizeit** [comment]
i am facing the same error

**Comment by moblizeit** [comment]
ok i found. the amount should be number and not in quotes

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
