### ISSUE TITLE
Newbie question - docs/examples

### ISSUE THREAD

**Issue by kjakub** [capacitor-community/stripe#55]
Hello,

please advise me how to begin in implementing this plugin, i am confused where to get docs, do i understand that i should look into [https://github.com/zyra/cordova-plugin-stripe](https://github.com/zyra/cordova-plugin-stripe) and then this plugin also bring apple pay and google pay methods where to get docs of them ?

**Comment by bleuscyther** [comment]
I think it moved to here:
https://capacitor-community.github.io/stripe/usage/

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
