### ISSUE TITLE
Is there no way to confirm a SetupIntent with Google Pay or Apple Pay

### ISSUE THREAD

**Issue by OrthoCube** [capacitor-community/stripe#56]
**Describe the bug**
In `confirmPaymentIntent`, there is an option to set `applePayOptions` or `googlePayOptions` so that the PaymentIntent can be paid using Apple Pay or Google Play. However, for subscriptions, confirming SetupIntents is needed, but `confirmSetupIntent` does not accept Apple Pay or Google Pay options. How is it possible to set up a subscription using Apple Pay and Google Pay?

**Expected behavior**
I was expecting that `confirmSetupIntent` would accept `applePayOptions` and `googlePlayOptions`

**Smartphone (please complete the following information):**
 - Device: iPhone / Android
 - OS: Latest
 - Browser: Safari / Chrome
 - Version: Latest

**Additional context**
We are trying to create a subscription page where a user can subscribe to a subscription using Stripe.

**Comment by ihadeed** [comment]
Setup Intents are for storing credit cards for later use. AFAIK that's not possible with Google/Apple pay.

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
