### ISSUE TITLE
validateExpiryDate always returns false on iOS

### ISSUE THREAD

**Issue by OrthoCube** [capacitor-community/stripe#58]
**Describe the bug**

Passing a valid expiry date results in `valid = false` for iOS (correctly returns `valid = true` on Android)

**To Reproduce**

```ts
Stripe.validateExpiryDate({ exp_month: 12, exp_year: 25 }).then(res => {
    this.expiryStatus = res.valid ? 'OK' : 'Invalid';
});
```

`this.expiryStatus` is set to 'Invalid'

**Expected behavior**

`this.expiryStatus` should be set to 'OK'.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.2
 - Browser: Safari
 - Version: 1.1.0

**Comment by giuseeFG** [comment]
Any news about this? @OrthoCube

**Comment by ktoala** [comment]
Same error

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
