### ISSUE TITLE
identifyCardBrand function always return unknown card type

### ISSUE THREAD

**Issue by pashyaaa** [capacitor-community/stripe#60]
**Describe the bug**
identifyCardBrand function always returns an unknown card type. I tried with real cards also but no luck. it always returns an unknown card.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16523454/111428504-98a9d380-871d-11eb-81d4-988ddfe94a59.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - Version - Version 89.0.4389.82 (Official Build) (64-bit)
 
**Additional context**
Same problem with validateCardNumber function it always returns card as valid.

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
