### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/stripe#61]
**Is your feature request related to a problem? Please describe.**
The Capacitor 3 RC is out! 🎉 This library should support the new version

**Describe the solution you'd like**
Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0

**Additional context**
The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

**Comment by danielehrhardt** [comment]
> **Is your feature request related to a problem? Please describe.**
> The Capacitor 3 RC is out! 🎉 This library should support the new version
> 
> **Describe the solution you'd like**
> Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0
> 
> **Additional context**
> The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

Maybe you could create a Pull Request?

**Comment by danielehrhardt** [comment]
https://github.com/capacitor-community/stripe/pull/74

**Comment by akkivinaya** [comment]
> **Is your feature request related to a problem? Please describe.**
> The Capacitor 3 RC is out! 🎉 This library should support the new version
> 
> **Describe the solution you'd like**
> Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0
> 
> **Additional context**
> The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

Hello Thomas,
Is the plug-in working for you in capacitor V3?

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
