### ISSUE TITLE
FPX / Wallet support

### ISSUE THREAD

**Issue by dodomui** [capacitor-community/stripe#65]
Looking for FPX / wallet integration.

Eg. 
https://stripe.com/docs/payments/fpx/accept-a-payment?platform=web
https://stripe.com/docs/payments/alipay/accept-a-payment?platform=web
https://stripe.com/docs/payments/grabpay/accept-a-payment?platform=web

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
