### ISSUE TITLE
Stripe is an empty object in IOS

### ISSUE THREAD

**Issue by nickmw11** [capacitor-community/stripe#66]
After following the example, I have a working implementation for Stripe in Android - whenever I try to initialize Stripe in IOS, it just doesn't seem to exist. If I log the stripe plugin, it's an empty object.

I can't tell if this is a bug, or if there is any additional configuration needed in ios. It looks like there is documentation for setting up Android, but not ios.

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.

**Comment by rdlabo** [comment]
@nickmw11 Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
