### ISSUE TITLE
Links in the documentation are invalid

### ISSUE THREAD

**Issue by wandexer** [capacitor-community/stripe#71]
**Describe the bug**
The links on the left of the documentation page (https://capacitor-community.github.io/stripe/) are invalid (Installation and usage examples result in 404).

**To Reproduce**
1. Go to https://capacitor-community.github.io/stripe/
2. Click on the links on the left for installation or usage examples

**Expected behavior**
Links should work

**Screenshots**
n.a.

**Desktop (please complete the following information):**
 - Browser Firefox

**Smartphone (please complete the following information):**
n.a.

**Additional context**

**Comment by rdlabo** [comment]
Thanks for issue!
Today this plugin of v3 is released. This not compatible with v1. All APIs have been revamped. So I will close this issue. If you still have the same problem, please create a new Issue. Thank you.
