### ISSUE TITLE
I am unable to listen events.Anbody can help me to get it done. Share some code snippet if possible. Stripe.addListener(completed: PaymentSheetEventsEnum.Completed, listenerFunc: () => void): PluginListenerHandle{

### ISSUE THREAD

**Issue by akkivinaya** [capacitor-community/stripe#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akkivinaya** [comment]
i was following wrong documentation

**Comment by rdlabo** [comment]
@akkivinaya You can check demo code: https://github.com/capacitor-community/stripe/blob/master/demo/angular/src/app/tab1/tab1.page.ts#L26-L44

Thanks.

**Comment by akkivinaya** [comment]
> @akkivinaya You can check demo code: https://github.com/capacitor-community/stripe/blob/master/demo/angular/src/app/tab1/tab1.page.ts#L26-L44
> 
> Thanks.

thanks..

**Comment by akkivinaya** [comment]
Thanks a lot, rdlabo..Any sample code for Google pay/Apple pay integration with the plugin?

**Comment by rdlabo** [comment]
not yet. Please check https://github.com/capacitor-community/stripe#stripeinitializationoptions .
And

- https://stripe.com/docs/payments/accept-a-payment#apple-pay
- https://stripe.com/docs/payments/accept-a-payment?platform=android#google-pay

Thanks.

**Comment by akkivinaya** [comment]
> not yet. Please check https://github.com/capacitor-community/stripe#stripeinitializationoptions .
> And
> 
> * https://stripe.com/docs/payments/accept-a-payment#apple-pay
> * https://stripe.com/docs/payments/accept-a-payment?platform=android#google-pay
> 
> Thanks.

Sample code is not available or it's not possible at the moment with plugin?

**Comment by rdlabo** [comment]
@akkivinaya This may be possible, I created API and connect Native SDK. This may be worked well. But sample code is not  implemented yet; 
Thanks.

**Comment by akkivinaya** [comment]
can you please share the pseudo code for the same if possible?
