### ISSUE TITLE
feat(native): Make customerEphemeralKeySecret optional

### ISSUE THREAD

**Issue by doszu** [capacitor-community/stripe#83]
When we use the plugin, we need to configure customerEphemeralKeySecret. We can set an empty string (''). This works for Android, but not iOS.
The implementation of checking this key is completely different on Android and iOS. Android checks if the keys are empty (== null), on iOS it checks an empty string (== '').
Can we make this variable optional?

**Comment by rdlabo** [comment]
@doszu Thanks issue. I will fixed this issue next version

**Comment by rdlabo** [comment]
released: https://github.com/capacitor-community/stripe/releases/tag/v3.0.1

**Comment by rdlabo** [comment]
@doszu Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
