### ISSUE TITLE
Payment Sheet Failed

### ISSUE THREAD

**Issue by max1018** [capacitor-community/stripe#89]
When trying to use the plugin on an iOS device or simulator I am getting a payment sheet failed message. However the code works just fine on web.

**Comment by PaintedShepherd** [comment]
Are you using the ephemeral key? If yes, then you have to use the id of the ephemeralResponse

**Comment by max1018** [comment]
Hi @PaintedShepherd , yes I am using the ephemeral key I am manually setting it at the. moment for testing purposes.

**Comment by rdlabo** [comment]
@max1018  First, you need to isolate whether the problem is with this plugin or something else. For that we are providing a demo. Please clone this repository and try https://github.com/capacitor-community/stripe/tree/master/demo/angular

**Comment by max1018** [comment]
@rdlabo , after i download the repo what commands do i need to run to install dependencies and use this on a simulator?

**Comment by rdlabo** [comment]
Please run `npm run cap && npx cap update && npx cap open ios` .

**Comment by max1018** [comment]
![Screen Shot 2021-08-02 at 8 44 32 AM](https://user-images.githubusercontent.com/14318898/127871577-213a9704-c5d8-44ee-aa1c-2ba45aa8e6c7.png)

**Comment by rdlabo** [comment]
Sorry, I forgot one command: `npm run build` in top repository.

**Comment by max1018** [comment]
The demo is working on my test device... not sure why its not in my application.

**Comment by rdlabo** [comment]
Maybe this is your backend api issue. Please check https://stripe.com/docs/payments/accept-a-payment?platform=ios#add-server-endpoint , and if not resolve, please ask stripe team.

**Comment by max1018** [comment]
I am manually entering the information so it shouldn't be my backend. Also it works on web. What reason would the paysheet pop up and then immediately fail ?

**Comment by rdlabo** [comment]
Manually? You should create by code: https://github.com/capacitor-community/stripe/blob/master/demo/server/src/app.controller.ts#L23-L26

The web will open the PaymentSheet even if the key is wrong, but iOS does not seem to. This is a Stripe specification, so please ask Stripe.

**Comment by max1018** [comment]
I create by code on the backend but then take response and manually enter in

**Comment by rdlabo** [comment]
@max1018 Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
