### ISSUE TITLE
validateExpiryDate always returns false on iOS 

### ISSUE THREAD

**Issue by Jud-Ken-Do** [capacitor-community/stripe#91]
**Describe the bug**
On the version 1.1.0 the validateExpiryDate always returns false on iOS

**To Reproduce**

const date: ValidateExpiryDateOptions = {
  exp_month,
  exp_year
}

async validateExpiry(date: ValidateExpiryDateOptions) {
  return await Stripe.validateExpiryDate(date);
}

**Expected behavior**
validateExpiry return false even for valid dates

**Additional context**
I'm aware that there is a new version, but for now I'm working using capacitor v2, is it possible to know where I can fix the swift code. 
Thank you :)

**Comment by rdlabo** [comment]
I see v2's validateExpiryDate method is not be implements. ( only always return false )

**Comment by rdlabo** [comment]
@Jud-Ken-Do Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
