### ISSUE TITLE
Plugin UI gets stuck on the Processing... spinner after payment authorization

### ISSUE THREAD

**Issue by metalllus** [capacitor-community/stripe#92]
If I attempt a payment with stripe test card 4000000000003220 (3D Secure 2) on Android, even though the payment completes successfully (verified in the Stripe Dashboard), the UI gets stuck after authorization on the Processing... screen, the green checkmark is never shown and the spinner keeps on spinning. The UI gets stuck no matter if this card is used as a new card or as a saved card, both cases exhibit the same phenomenon.

![Screenshot_1629161128](https://user-images.githubusercontent.com/48943750/129646377-7cb9fac5-40b1-46b8-ba4a-67dfb47a1e84.png)

On Android I tried this also with 4242424242424242 and 4000000000003063 cards, both work without issues. Android testing was done on a simulator as well as on a Pixel 4a 5G physical device with the same result.
On iPhone, everything works fine with all three test cards.

Could someone please give this a spin on Android to check?

**Comment by rdlabo** [comment]
This may not plugin issue. Please contact with Stripe team. Thanks.
