### ISSUE TITLE
How to achieve displaying the PaymentSheet in a language of choice on iPhone

### ISSUE THREAD

**Issue by metalllus** [capacitor-community/stripe#93]
I am trying to display the PaymentSheet in Slovak language (Slovak is supported by Stripe) on iPhone. 

These are my regional options on the iPhone:
![2021-08-17_12-13-47](https://user-images.githubusercontent.com/48943750/129708128-a9549d79-248b-4c70-99b7-92a5e307611d.png)

This is my setting in Info.plist
![2021-08-17_12-15-26](https://user-images.githubusercontent.com/48943750/129708436-ac1ab97d-2d88-44e6-a0a9-f67ca960c010.png)

These are my localization settings:
![2021-08-17_12-18-34](https://user-images.githubusercontent.com/48943750/129708929-94d434cd-ef70-4ee6-b879-0bbc43c3f746.png)

I must be missing something because I always get the PaymentSheet in English. On Android I get Slovak as expected. Please help.

**Comment by rdlabo** [comment]
@metalllus Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
