### ISSUE TITLE
The customer has not entered their payment method.

### ISSUE THREAD

**Issue by dheerajkhokhar** [capacitor-community/stripe#94]
Hi, I try to implement both the method PaymentSheet and PaymentFlow in ionic react project but every time payment failed, this error message ("The customer has not entered their payment method.") is shown in stripe dashboard. Can you please tell me how to solve this issue.

Thanks:-

Code:- 
```ts
const { paymentIntent, ephemeralKey, customer } = //HTTP SERVER REQUEST RESPONSE;
Stripe.createPaymentFlow({
  paymentIntentClientSecret: paymentIntent,
  customerEphemeralKeySecret: ephemeralKey,
  customerId: customer,
  merchantDisplayName: 'App Name',
  style: 'alwaysDark',
}).then((createPaymentSheetResponse)=>{
  console.log("createPaymentSheetResponse - ", createPaymentSheetResponse);
  Stripe.presentPaymentFlow().then(finalResponse =>{
    console.log("finalResponse - ", finalResponse);
  }).catch((error)=>{
  })
}).catch((error)=>{
})
```

**Comment by rdlabo** [comment]
`createPaymentFlow` require `confirmPaymentFlow`.
Please check demo: https://github.com/capacitor-community/stripe/blob/master/demo/angular/src/app/tab3/tab3.page.ts#L120-L131

Thanks.

**Comment by rdlabo** [comment]
@dheerajkhokhar Did you adapt this plugin for production? If yes, please tell us what app. Please help us to develop this plugin in 2022.
https://github.com/capacitor-community/stripe/issues/145
Thanks.
